// Copyright 2019 Jason Ertel (github.com/jertel).
// Copyright 2020-2025 Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
// or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
// https://securityonion.net/license; you may not use this file except in compliance with the
// Elastic License 2.0.

package model

import (
	"bytes"
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"hash"
	"io"
	"net/http"
	"strings"
	"time"
)

const CASE_STATUS_NEW = "new"

// @Description The Auditable fields are read-only. They are generated by the server.
type Auditable struct {
	// The ID assigned to this object by the server. This is a read-only field.
	Id string `json:"id,omitempty" example:"PdFc-JIBLkNJ8-bDfz47"`
	// The date and time that this object was created. This is a read-only field.
	CreateTime *time.Time `json:"createTime" example:"2024-11-14T15:03:22Z"`
	// The date and time that this object was last modified. This is a read-only field.
	UpdateTime *time.Time `json:"updateTime,omitempty" example:"2024-11-14T15:33:02Z"`
	// The user ID (or API client ID) that initated this event. This is a read-only field.
	UserId string `json:"userId" example:"socl_my_new_client"`
	// The kind of object. This is a read-only field.
	Kind string `json:"kind,omitempty" example:"case"`
	// The operation that was applied to the object. This is a read-only field.
	Operation string `json:"operation,omitempty" example:"create"`
}

type Case struct {
	Auditable
	// The date and time that the case status was changed to 'in progress'. This is a read-only field.
	StartTime *time.Time `json:"startTime" example:"2024-11-14T15:03:22Z" validate:"optional"`
	// The date and time that the case was completed. A case is completed when the status is changed to 'closed'. This is a read-only field.
	CompleteTime *time.Time `json:"completeTime" example:"2024-11-14T15:33:02Z" validate:"optional"`
	// The brief case title or summary
	Title string `json:"title" example:"Possible intrusion via SMTP server" validate:"optional"`
	// The full description of the case.
	Description string `json:"description" example:"Discovered anomalous events during the overnight hours of November 14-15. Atypical large network volumes passed through SMTP server." validate:"optional"`
	// The priority of the case. Lower values typically represent increasing importance.
	Priority int `json:"priority" example:"1" validate:"optional"`
	// The serverity of the case. Typical values are: critical, high, medium, low
	Severity string `json:"severity" example:"high" validate:"optional"`
	// The state of the case. Typical values are: new, in progress, closed
	Status string `json:"status" example:"new" validate:"optional"`
	// A case ID representing the case to use as a template when creating this case. The template case fields will be copied into the new case.
	Template string `json:"template" example:"some_case_id_to_be_used_as_template" validate:"optional"`
	// The Traffic Light Protocol value.
	Tlp string `json:"tlp" example:"red" validate:"optional"`
	// The Permissiable Actions Protocol value.
	Pap string `json:"pap" example:"white" validate:"optional"`
	// A category is a way to group similar cases together and can be arbitrary values, or static values, depending on how the system if configured.
	Category string `json:"category" example:"general" validate:"optional"`
	// The user ID that is assigned to work on this case.
	AssigneeId string `json:"assigneeId" example:"022d1936-6ca3-49c1-b3ee-6a5b27d1b8b1" validate:"optional"`
	// A tag is another way to group similar cases together and can be arbitrary values, or static values, depending on how the system if configured.
	Tags []string `json:"tags" example:"pending,confirmed" validate:"optional"`
}

func NewCase() *Case {
	newCase := &Case{}
	return newCase
}

func (socCase *Case) ProcessWorkflowForStatus(oldCase *Case) {
	now := time.Now()
	if socCase.Status == "closed" && oldCase.Status != "closed" {
		socCase.CompleteTime = &now
	}
	if oldCase.StartTime != nil && !oldCase.StartTime.IsZero() {
		socCase.StartTime = oldCase.StartTime
	} else if socCase.Status == "in progress" && oldCase.Status != "in progress" {
		socCase.StartTime = &now
	}
}

type Comment struct {
	Auditable
	// The case ID for which this comment is to be attached, or is already attached.
	CaseId string `json:"caseId" example:"PdFc-JIBLkNJ8-bDfz47" validate:"required"`
	// The comment content itself. Can contain limited markdown syntax.
	Description string `json:"description" example:"Discovered another anomaly around the same time involving missing logs on server xyz." validate:"required"`
	// The number of hours spent on the work referenced in this comment. Can be a decimal value.
	Hours float64 `json:"hours" example:"2.5" validate:"optional"`
}

func NewComment() *Comment {
	newComment := &Comment{}
	return newComment
}

type RelatedEvent struct {
	Auditable
	// The case ID for which this related event is to be attached, or is already attached.
	CaseId string `json:"caseId" example:"PdFc-JIBLkNJ8-bDfz47" validate:"required"`
	// A mapping of related event field names and their values.
	Fields map[string]interface{} `json:"fields" example:"client.ip:1.2.3.4,client.port:1099" validate:"required"`
}

func NewRelatedEvent() *RelatedEvent {
	newRelatedEvent := &RelatedEvent{}
	now := time.Now()
	newRelatedEvent.CreateTime = &now
	newRelatedEvent.Fields = make(map[string]interface{})
	return newRelatedEvent
}

type AttachEventCriteria struct {
	// The case ID for which this related event is to be attached, or is already attached.
	CaseId string `json:"caseId" example:"PdFc-JIBLkNJ8-bDfz47" validate:"required"`
	// A mapping of related event field names and their values.
	Fields map[string]interface{} `json:"fields" example:"client.ip:1.2.3.4,client.port:1099" validate:"required"`
	// The date range to use for searching for matching events
	DateRange string `json:"dateRange,omitempty" example:"2024/12/03 02:31:35 PM - 2024/12/04 02:31:35 PM"`
	// The date range format. If unsure how to use this then use the example value exactly as shown.
	DateRangeFormat string `json:"dateRangeFormat,omitempty" example:"2006/01/02 3:04:05 PM"`
	// The timezone to use with the date range
	Timezone string `json:"timezone,omitempty" example:"America/New_York"`
	// Whether to attach events that are already escalated to a case: true = act on escalated events, false = act on unescalated events
	Escalate bool `json:"escalate" example:"false"`
	// Whether to attach events that are already acknowledged: true = act on acknowledged events, false = act on unacknowledged events
	Acknowledge bool `json:"acknowledge" example:"true"`
}

func NewAttachEventCriteria() *AttachEventCriteria {
	criteria := &AttachEventCriteria{}
	criteria.Fields = make(map[string]interface{})
	return criteria
}

type Artifact struct {
	Auditable
	// The case ID for which this artifact is to be attached, or is already attached.
	CaseId string `json:"caseId" example:"PdFc-JIBLkNJ8-bDfz47" validate:"required"`
	// The group type as set by the server. This is an internal, read-only field.
	GroupType string `json:"groupType" example:"evidence"`
	// The group ID as set by the server. This is an internal, read-only field.
	GroupId string `json:"groupId" example:""`
	// The artifact type as set by the server. This is an internal, read-only field.
	ArtifactType string `json:"artifactType" example:"ip" validate:"required"`
	// The value of this artifact. Essentially this is the content of the artifact itself, such as an IP address, a hostname, a stream of file bytes, etc.
	Value string `json:"value" example:"1.2.3.4" validate:"required"`
	// The mime type of the artifact stream. This field is determined by the server upon file upload and is read-only.
	MimeType string `json:"mimeType" example:"application/json"`
	// The length of the artifact stream. This field is determined by the server upon file upload and is ready-only.
	StreamLen int `json:"streamLength" example:"4096"`
	// The stream ID of the artifact stream. This field is determined by the server upon file upload and is ready-only.
	StreamId string `json:"streamId" example:"f2fS-DajPqlMo-221Nmn"`
	// The traffic light protocol value for this artifact.
	Tlp string `json:"tlp" example:"red" validate:"optional"`
	// Tags to assign to this artifact.
	Tags []string `json:"tags" example:"pending,unconfirmed" validate:"optional"`
	// A description that explains how this artifact relates to the case.
	Description string `json:"description" example:"Additional supporting evidence" validate:"optional"`
	// A flag representing whether this artifact is an indicator of compromise (IoC).
	Ioc bool `json:"ioc" example:"false" validate:"optional"`
	// An MD5 hash of the artifact stream. This field is determined by the server upon file upload and is ready-only.
	Md5 string `json:"md5" example:"d9cca721a735dac4efe709e0f3518373" validate:"optional"`
	// A SHA-1 hash of the artifact stream. This field is determined by the server upon file upload and is ready-only.
	Sha1 string `json:"sha1" example:"a0571c5b9493187adb5bd07ad0faf279a86251df" validate:"optional"`
	// A SHA-256 hash of the artifact stream. This field is determined by the server upon file upload and is ready-only.
	Sha256 string `json:"sha256" example:"9c1f8398f5a92eee44aee58d000a4dc1705f9c25e29683f7730215bc1274cff1" validate:"optional"`
	// A flag representing whether this file artifact is protected. A protected file will be automatically zipped by the server before being retrieved, to avoid accidentally executing a potentially harmful attachment.
	Protected bool `json:"protected" example:"false" validate:"optional"`
}

func NewArtifact() *Artifact {
	newArtifact := &Artifact{}
	now := time.Now()
	newArtifact.CreateTime = &now
	return newArtifact
}

type ArtifactStream struct {
	Auditable
	// The byte stream of the file artifact.
	Content string `json:"content" example:"(binary)" validate:"required"`
}

func NewArtifactStream() *ArtifactStream {
	newStream := &ArtifactStream{}
	now := time.Now()
	newStream.CreateTime = &now
	return newStream
}

func (stream *ArtifactStream) hashBytes(hasher hash.Hash, input []byte) string {
	hasher.Write(input)
	output := hasher.Sum(nil)
	return fmt.Sprintf("%x", output)
}

func (stream *ArtifactStream) Write(reader io.Reader) (int, string, string, string, string, error) {
	var buffer bytes.Buffer
	var mimeType, md5hash, sha1hash, sha256hash string

	// Collect bytes in memory
	copyLen, err := buffer.ReadFrom(reader)
	if err == nil {
		raw := buffer.Bytes()
		stream.Content = base64.StdEncoding.EncodeToString(raw)
		mimeType = http.DetectContentType(raw)
		md5hash = stream.hashBytes(md5.New(), raw)
		sha1hash = stream.hashBytes(sha1.New(), raw)
		sha256hash = stream.hashBytes(sha256.New(), raw)
	}
	return int(copyLen), mimeType, md5hash, sha1hash, sha256hash, err
}

func (stream *ArtifactStream) Read() io.Reader {
	return base64.NewDecoder(base64.StdEncoding, strings.NewReader(stream.Content))
}
