// Copyright 2019 Jason Ertel (github.com/jertel).
// Copyright 2020-2025 Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
// or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
// https://securityonion.net/license; you may not use this file except in compliance with the
// Elastic License 2.0.

package model

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/apex/log"
	socjson "github.com/security-onion-solutions/securityonion-soc/json"
)

const API_CLIENT_PREFIX = "socl_"

type Subgrid struct {
	// A unique, admin-assigned identifier string for this subgrid
	Id string `json:"id" example:"subgrid_b"`
	// The base URL for this subgrid, used by manager overseer nodes to access this subgrid
	ManagerUrl string `json:"managerUrl" example:"https://subgrid_host_name"`
	// The Client ID generated by the API Client interface, used to authenticate to this subgrid
	ClientId string `json:"clientId" example:"socl_my_client_id"`
	// The Client Secret generated by the API Client interface, used to authenticate to this subgrid
	ClientSecret string `json:"clientSecret" example:"xSff24sSvkKJaMN24"`
	// Flag that controls whether this subgrid is enabled or not
	Enabled bool `json:"enabled" example:"false"`
	// Subgrid Certificate Authority cert in PEM format, if available"
	CaCertificate string `json:"caCertificate" example:"-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----\n"`
	// Flag that allows the skipping of TLS certification validation; useful for test environments
	SkipTlsVerify bool `json:"skipTlsVerify" example:"true"`
	// Ephemeral access token used internally within SOC
	AccessToken string `json:"-"`
	// Ephemeral access token expiration date and time, user internally within SOC
	TokenExpiration time.Time `json:"-"`
}

func (grid *Subgrid) Verify() error {
	if !grid.Enabled {
		return nil
	}
	if len(strings.TrimSpace(grid.Id)) == 0 {
		return errors.New("invalid subgrid ID; must not be empty")
	}
	if len(strings.TrimSpace(grid.ManagerUrl)) == 0 {
		return errors.New("invalid subgrid Manager URL; must not be empty")
	}
	if strings.Index(grid.ManagerUrl, "https://") != 0 {
		return errors.New("invalid subgrid Manager URL; must specify the HTTPS protocol")
	}
	if len(strings.TrimSpace(grid.ClientId)) == 0 {
		return errors.New("invalid subgrid client ID; must not be empty")
	}
	if strings.Index(grid.ClientId, API_CLIENT_PREFIX) != 0 {
		return errors.New("invalid subgrid client ID; malformed client ID")
	}
	if len(strings.TrimSpace(grid.ClientSecret)) == 0 {
		return errors.New("invalid subgrid client secret; must not be empty")
	}
	return nil
}

func (grid *Subgrid) MarshalJSON() ([]byte, error) {
	tmp := *grid
	tmp.ClientSecret = ""
	return json.Marshal(tmp)
}

func (grid *Subgrid) getHttpsClient() *http.Client {
	tlsConfig := &tls.Config{}

	if grid.SkipTlsVerify {
		tlsConfig.InsecureSkipVerify = true
	}

	if len(strings.TrimSpace(grid.CaCertificate)) > 0 {
		log.WithField("subgridId", grid.Id).Debug("adding subgrid CA to root CA list for http client")
		caCertPool := x509.NewCertPool()
		caCertPool.AppendCertsFromPEM([]byte(grid.CaCertificate))
		tlsConfig.RootCAs = caCertPool
	}

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}

	return client
}

func (grid *Subgrid) refreshAccessToken() error {
	if grid.TokenExpiration.After(time.Now().Add(time.Minute*5)) && grid.AccessToken != "" {
		// Token is valid for at least 5 more minutes, no need to refresh
		return nil
	}

	tokenUrl := fmt.Sprintf("%s/oauth2/token", strings.TrimSuffix(grid.ManagerUrl, "/"))
	data := url.Values{}
	data.Set("grant_type", "client_credentials")

	client := grid.getHttpsClient()
	req, err := http.NewRequest("POST", tokenUrl, strings.NewReader(data.Encode()))
	if err != nil {
		return fmt.Errorf("failed to create token request: %v", err)
	}
	req.SetBasicAuth(grid.ClientId, grid.ClientSecret)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to get token: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to get token, status code: %d", resp.StatusCode)
	}

	var tokenResponse map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResponse); err != nil {
		return fmt.Errorf("failed to decode token response: %v", err)
	}

	accessToken, ok := tokenResponse["access_token"].(string)
	if !ok {
		return errors.New("access_token not found in token response")
	}

	expiresIn, ok := tokenResponse["expires_in"].(float64)
	if !ok {
		return errors.New("expires_in not found in token response")
	}

	grid.AccessToken = accessToken
	grid.TokenExpiration = time.Now().Add(time.Second * time.Duration(int(expiresIn))) // expires_in is in seconds

	log.WithFields(log.Fields{
		"subgridId": grid.Id,
		"expiresIn": expiresIn,
		"expiresAt": grid.TokenExpiration,
	}).Debug("Subgrid access token refreshed")

	return nil
}

func (grid *Subgrid) MakeApiCall(method string, url string, body io.Reader) ([]byte, error) {
	if err := grid.refreshAccessToken(); err != nil {
		return nil, fmt.Errorf("failed to refresh access token: %v", err)
	}

	apiURL := fmt.Sprintf("%s/connect%s", strings.TrimSuffix(grid.ManagerUrl, "/"), url)

	client := grid.getHttpsClient()
	req, err := http.NewRequest(method, apiURL, body)
	if err != nil {
		return nil, fmt.Errorf("failed to create API request: %v", err)
	}

	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", grid.AccessToken))

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to make API call: %v", err)
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("API call failed with status code: %d", resp.StatusCode)
	}

	return io.ReadAll(resp.Body)
}

func (grid *Subgrid) GetGridNodes() ([]*Node, error) {
	bytes, err := grid.MakeApiCall("GET", "/grid", nil)
	if err != nil {
		return nil, err
	}

	nodes := make([]*Node, 0)
	err = socjson.LoadJson(bytes, &nodes)
	if err != nil {
		return nil, err
	}

	for _, node := range nodes {
		node.GridId = grid.Id
	}

	return nodes, nil
}
