// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server/modules/detections (interfaces: DetailedDetectionEngine)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_detaileddetectionengine.go -package mock . DetailedDetectionEngine
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	fs "io/fs"
	http "net/http"
	os "os"
	exec "os/exec"
	reflect "reflect"
	time "time"

	log "github.com/apex/log"
	gomock "go.uber.org/mock/gomock"
)

// MockDetailedDetectionEngine is a mock of DetailedDetectionEngine interface.
type MockDetailedDetectionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDetailedDetectionEngineMockRecorder
	isgomock struct{}
}

// MockDetailedDetectionEngineMockRecorder is the mock recorder for MockDetailedDetectionEngine.
type MockDetailedDetectionEngineMockRecorder struct {
	mock *MockDetailedDetectionEngine
}

// NewMockDetailedDetectionEngine creates a new mock instance.
func NewMockDetailedDetectionEngine(ctrl *gomock.Controller) *MockDetailedDetectionEngine {
	mock := &MockDetailedDetectionEngine{ctrl: ctrl}
	mock.recorder = &MockDetailedDetectionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetailedDetectionEngine) EXPECT() *MockDetailedDetectionEngineMockRecorder {
	return m.recorder
}

// CloneRepo mocks base method.
func (m *MockDetailedDetectionEngine) CloneRepo(ctx context.Context, path, repo string, branch *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneRepo", ctx, path, repo, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneRepo indicates an expected call of CloneRepo.
func (mr *MockDetailedDetectionEngineMockRecorder) CloneRepo(ctx, path, repo, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneRepo", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).CloneRepo), ctx, path, repo, branch)
}

// DeleteFile mocks base method.
func (m *MockDetailedDetectionEngine) DeleteFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockDetailedDetectionEngineMockRecorder) DeleteFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).DeleteFile), path)
}

// ExecCommand mocks base method.
func (m *MockDetailedDetectionEngine) ExecCommand(cmd *exec.Cmd) ([]byte, int, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCommand", cmd)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(time.Duration)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ExecCommand indicates an expected call of ExecCommand.
func (mr *MockDetailedDetectionEngineMockRecorder) ExecCommand(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCommand", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).ExecCommand), cmd)
}

// MakeRequest mocks base method.
func (m *MockDetailedDetectionEngine) MakeRequest(arg0 *http.Request, arg1 bool) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequest", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequest indicates an expected call of MakeRequest.
func (mr *MockDetailedDetectionEngineMockRecorder) MakeRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).MakeRequest), arg0, arg1)
}

// PauseIntegrityChecker mocks base method.
func (m *MockDetailedDetectionEngine) PauseIntegrityChecker() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PauseIntegrityChecker")
}

// PauseIntegrityChecker indicates an expected call of PauseIntegrityChecker.
func (mr *MockDetailedDetectionEngineMockRecorder) PauseIntegrityChecker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseIntegrityChecker", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).PauseIntegrityChecker))
}

// PullRepo mocks base method.
func (m *MockDetailedDetectionEngine) PullRepo(ctx context.Context, path string, branch *string) (bool, bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRepo", ctx, path, branch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// PullRepo indicates an expected call of PullRepo.
func (mr *MockDetailedDetectionEngineMockRecorder) PullRepo(ctx, path, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRepo", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).PullRepo), ctx, path, branch)
}

// ReadDir mocks base method.
func (m *MockDetailedDetectionEngine) ReadDir(path string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockDetailedDetectionEngineMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).ReadDir), path)
}

// ReadFile mocks base method.
func (m *MockDetailedDetectionEngine) ReadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockDetailedDetectionEngineMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).ReadFile), path)
}

// RemoveAll mocks base method.
func (m *MockDetailedDetectionEngine) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockDetailedDetectionEngineMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).RemoveAll), path)
}

// ResumeIntegrityChecker mocks base method.
func (m *MockDetailedDetectionEngine) ResumeIntegrityChecker() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumeIntegrityChecker")
}

// ResumeIntegrityChecker indicates an expected call of ResumeIntegrityChecker.
func (mr *MockDetailedDetectionEngineMockRecorder) ResumeIntegrityChecker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeIntegrityChecker", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).ResumeIntegrityChecker))
}

// Stat mocks base method.
func (m *MockDetailedDetectionEngine) Stat(path string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", path)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockDetailedDetectionEngineMockRecorder) Stat(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).Stat), path)
}

// Sync mocks base method.
func (m *MockDetailedDetectionEngine) Sync(arg0 *log.Entry, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockDetailedDetectionEngineMockRecorder) Sync(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).Sync), arg0, arg1)
}

// WalkDir mocks base method.
func (m *MockDetailedDetectionEngine) WalkDir(root string, fn fs.WalkDirFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalkDir", root, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalkDir indicates an expected call of WalkDir.
func (mr *MockDetailedDetectionEngineMockRecorder) WalkDir(root, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalkDir", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).WalkDir), root, fn)
}

// WriteFile mocks base method.
func (m *MockDetailedDetectionEngine) WriteFile(path string, contents []byte, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, contents, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockDetailedDetectionEngineMockRecorder) WriteFile(path, contents, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockDetailedDetectionEngine)(nil).WriteFile), path, contents, perm)
}
