#!/usr/bin/env node

// Build script to bundle hunt modules into a single file
// This creates a browser-compatible version without ES6 modules

const fs = require('fs');
const path = require('path');

const outputFile = path.join(__dirname, 'html/js/routes/hunt-bundled.js');
const modulesDir = path.join(__dirname, 'html/js/routes/hunt');

// Read all module files
const modules = {
  data: fs.readFileSync(path.join(modulesDir, 'data.js'), 'utf8'),
  query: fs.readFileSync(path.join(modulesDir, 'query.js'), 'utf8'),
  routing: fs.readFileSync(path.join(modulesDir, 'routing.js'), 'utf8'),
  dataHandlers: fs.readFileSync(path.join(modulesDir, 'dataHandlers.js'), 'utf8'),
  actions: fs.readFileSync(path.join(modulesDir, 'actions.js'), 'utf8'),
  charts: fs.readFileSync(path.join(modulesDir, 'charts.js'), 'utf8'),
  playbook: fs.readFileSync(path.join(modulesDir, 'playbook.js'), 'utf8'),
  ai: fs.readFileSync(path.join(modulesDir, 'ai.js'), 'utf8'),
  ui: fs.readFileSync(path.join(modulesDir, 'ui.js'), 'utf8'),
  localStorage: fs.readFileSync(path.join(modulesDir, 'localStorage.js'), 'utf8'),
  methods: fs.readFileSync(path.join(modulesDir, 'methods.js'), 'utf8'),
};

// Function to extract the export default content
function extractExportDefault(moduleContent, keepImports = false) {
  let content = moduleContent;
  
  if (!keepImports) {
    // Remove import statements
    content = content.replace(/^import\s+.*?from\s+['"].*?['"];?\s*$/gm, '');
  }
  
  // Extract content after 'export default'
  const exportMatch = content.match(/export\s+default\s+({[\s\S]*});?\s*$/);
  if (exportMatch) {
    return exportMatch[1];
  }
  return '{}';
}

// Function to extract additional methods from methods.js
function extractMethodsContent(moduleContent) {
  // Find the export default section
  const exportMatch = moduleContent.match(/export\s+default\s+{([\s\S]*?)};?\s*$/);
  if (!exportMatch) return '';
  
  let exportContent = exportMatch[1];
  
  // Remove all the spread operations (e.g., ...queryMethods)
  exportContent = exportContent.replace(/^\s*\.\.\.[\w]+,?\s*$/gm, '');
  
  // Trim whitespace and trailing commas
  return exportContent.trim().replace(/,\s*$/, '');
}

// Extract additional methods from methods.js
const additionalMethodsCode = extractMethodsContent(modules.methods);

// Build the bundled file
let bundledContent = `// Copyright 2019 Jason Ertel (github.com/jertel).
// Copyright 2020-2025 Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
// or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
// https://securityonion.net/license; you may not use this file except in compliance with the
// Elastic License 2.0.

// This file is auto-generated by build-hunt.js
// It bundles all hunt modules into a single browser-compatible file

// Only load template in browser environment
if (typeof loadPageTemplate !== 'undefined') {
  loadPageTemplate('page-hunt', 'pages/hunt.html');
}

// Constants used by various modules
const RELATIVE_TIME_SECONDS = 10;
const RELATIVE_TIME_MINUTES = 20;
const RELATIVE_TIME_HOURS   = 30;
const RELATIVE_TIME_DAYS    = 40;
const RELATIVE_TIME_WEEKS   = 50;
const RELATIVE_TIME_MONTHS  = 60;
const FILTER_INCLUDE = 'INCLUDE';
const FILTER_EXCLUDE = 'EXCLUDE';
const FILTER_EXACT = 'EXACT';
const FILTER_DRILLDOWN = 'DRILLDOWN';

// Extract module contents
const huntData = ${extractExportDefault(modules.data)};

const queryMethods = ${extractExportDefault(modules.query)};

const routingMethods = ${extractExportDefault(modules.routing)};

const dataHandlerMethods = ${extractExportDefault(modules.dataHandlers)};

const actionMethods = ${extractExportDefault(modules.actions)};

const chartMethods = ${extractExportDefault(modules.charts)};

const playbookMethods = ${extractExportDefault(modules.playbook)};

const aiMethods = ${extractExportDefault(modules.ai)};

const uiMethods = ${extractExportDefault(modules.ui)};

const localStorageMethods = ${extractExportDefault(modules.localStorage)};

// Combine all methods
const huntMethods = {
  ...queryMethods,
  ...routingMethods,
  ...dataHandlerMethods,
  ...actionMethods,
  ...chartMethods,
  ...playbookMethods,
  ...aiMethods,
  ...uiMethods,
  ...localStorageMethods,
  ${additionalMethodsCode ? additionalMethodsCode + ',' : ''}
  isAdvanced() {
    return this.advanced || this.isCategory('hunt') || this.isCategory('cases');
  },
  loading() {
    return this.$root.loading;
  }
};

// Create hunt component
const huntComponent = {
  template: '#page-hunt',
  data() {
    const data = huntData;
    data.i18n = this.$root.i18n;
    data.bulkActions = [
      { title: this.$root.i18n.enable, value: 'enable' },
      { title: this.$root.i18n.disable, value: 'disable' },
      { title: this.$root.i18n.delete, value: 'delete' },
    ];
    return data;
  },
  created() {
    this.$root.initializeCharts();
    this.initializeTimeAndIntervals();
  },
  beforeUnmount() {
    this.$root.setSubtitle("");
    this.stopRefreshTimer();
    this.$root.unsubscribe('detections:bulkUpdate', this.bulkUpdateReport);
    this.$root.unsubscribe('related:bulkCreate', this.bulkUpdateReport);

    if (this.isCategory('alerts')) {
      window.removeEventListener('resize', this.calculateEventColumnWidth);
    }
  },
  mounted() {
    this.$root.startLoading();
    this.category = this.$route.path.replace("/", "");
    this.$root.loadParameters(this.category, this.initHunt);

    if (this.isCategory('detections')) {
      this.$root.subscribe('detections:bulkUpdate', this.bulkUpdateReport);
    }

    if (this.isCategory('alerts') || this.isCategory('hunt')) {
      this.$root.subscribe('related:bulkCreate', this.bulkUpdateReport);
    }

    if (this.isCategory('alerts')) {
      window.addEventListener('resize', this.calculateEventColumnWidth);
    }
  },
  watch: {
    '$route': 'loadData',
    'groupBySortBy': 'saveLocalSettings',
    'groupBySortDesc': 'saveLocalSettings',
    'groupByItemsPerPage': 'groupByItemsPerPageChanged',
    'groupByLimit': 'groupByLimitChanged',
    'sortBy': 'saveLocalSettings',
    'sortDesc': 'saveLocalSettings',
    'itemsPerPage': 'itemsPerPageChanged',
    'eventLimit': 'eventLimitChanged',
    'relativeTimeValue': 'saveLocalSettings',
    'relativeTimeUnit': 'saveLocalSettings',
    'autohunt': 'saveLocalSettings',
    'autoRefreshInterval': 'resetRefreshTimer',
    'showDetailsPanel': 'toggleShowDetailsPanel',
    'advanced': 'saveLocalSettings',
  },
  methods: huntMethods
};

// Register routes (only in browser environment)
if (typeof routes !== 'undefined') {
  routes.push({ path: '/hunt', name: 'hunt', component: huntComponent});

  const alertsComponent = Object.assign({}, huntComponent);
  routes.push({ path: '/alerts', name: 'alerts', component: alertsComponent});

  const casesComponent = Object.assign({}, huntComponent);
  routes.push({ path: '/cases', name: 'cases', component: casesComponent});

  const dashboardsComponent = Object.assign({}, huntComponent);
  routes.push({ path: '/dashboards', name: 'dashboards', component: dashboardsComponent});

  const detectionsComponent = Object.assign({}, huntComponent);
  routes.push({ path: '/detections', name: 'detections', component: detectionsComponent });
}
`;

// Write the bundled file
fs.writeFileSync(outputFile, bundledContent);
console.log(`Hunt modules bundled successfully to: ${outputFile}`);

// Export for testing if running in Node.js environment
const testExports = `
// Export for testing when in Node.js environment
if (typeof module !== 'undefined' && module.exports) {
  // Mock globals for testing
  if (typeof global !== 'undefined') {
    global.routes = global.routes || [];
    global.loadPageTemplate = global.loadPageTemplate || function() {};
    global.moment = global.moment || { tz: { guess: () => 'UTC' } };
    global.$ = global.$ || global.jQuery || function() { 
      return { 
        daterangepicker: function() {}, 
        on: function() {},
        0: { value: '' }
      }; 
    };
    global.jsyaml = global.jsyaml || { load: () => ({}), FAILSAFE_SCHEMA: {} };
  }
  
  module.exports = {
    huntData,
    huntMethods,
    huntComponent,
    queryMethods,
    routingMethods,
    dataHandlerMethods,
    actionMethods,
    chartMethods,
    playbookMethods,
    aiMethods,
    uiMethods,
    localStorageMethods
  };
}
`;

fs.appendFileSync(outputFile, testExports);