// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: GridMembersstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_gridmembersstore.go -package mock . GridMembersstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGridMembersstore is a mock of GridMembersstore interface.
type MockGridMembersstore struct {
	ctrl     *gomock.Controller
	recorder *MockGridMembersstoreMockRecorder
	isgomock struct{}
}

// MockGridMembersstoreMockRecorder is the mock recorder for MockGridMembersstore.
type MockGridMembersstoreMockRecorder struct {
	mock *MockGridMembersstore
}

// NewMockGridMembersstore creates a new mock instance.
func NewMockGridMembersstore(ctrl *gomock.Controller) *MockGridMembersstore {
	mock := &MockGridMembersstore{ctrl: ctrl}
	mock.recorder = &MockGridMembersstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGridMembersstore) EXPECT() *MockGridMembersstoreMockRecorder {
	return m.recorder
}

// GetMembers mocks base method.
func (m *MockGridMembersstore) GetMembers(ctx context.Context) ([]*model.GridMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx)
	ret0, _ := ret[0].([]*model.GridMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockGridMembersstoreMockRecorder) GetMembers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockGridMembersstore)(nil).GetMembers), ctx)
}

// Import mocks base method.
func (m *MockGridMembersstore) Import(ctx context.Context, node, file, importer string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, node, file, importer)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockGridMembersstoreMockRecorder) Import(ctx, node, file, importer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockGridMembersstore)(nil).Import), ctx, node, file, importer)
}

// ManageMember mocks base method.
func (m *MockGridMembersstore) ManageMember(ctx context.Context, operation, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManageMember", ctx, operation, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ManageMember indicates an expected call of ManageMember.
func (mr *MockGridMembersstoreMockRecorder) ManageMember(ctx, operation, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManageMember", reflect.TypeOf((*MockGridMembersstore)(nil).ManageMember), ctx, operation, id)
}

// RunTroubleshoot mocks base method.
func (m *MockGridMembersstore) RunTroubleshoot(ctx context.Context, node, script string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTroubleshoot", ctx, node, script)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTroubleshoot indicates an expected call of RunTroubleshoot.
func (mr *MockGridMembersstoreMockRecorder) RunTroubleshoot(ctx, node, script any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTroubleshoot", reflect.TypeOf((*MockGridMembersstore)(nil).RunTroubleshoot), ctx, node, script)
}

// SendFile mocks base method.
func (m *MockGridMembersstore) SendFile(ctx context.Context, node, from, to string, cleanup bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", ctx, node, from, to, cleanup)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFile indicates an expected call of SendFile.
func (mr *MockGridMembersstoreMockRecorder) SendFile(ctx, node, from, to, cleanup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockGridMembersstore)(nil).SendFile), ctx, node, from, to, cleanup)
}
