// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: DetectionEngine)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_detectionengine.go -package mock . DetectionEngine
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDetectionEngine is a mock of DetectionEngine interface.
type MockDetectionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDetectionEngineMockRecorder
}

// MockDetectionEngineMockRecorder is the mock recorder for MockDetectionEngine.
type MockDetectionEngineMockRecorder struct {
	mock *MockDetectionEngine
}

// NewMockDetectionEngine creates a new mock instance.
func NewMockDetectionEngine(ctrl *gomock.Controller) *MockDetectionEngine {
	mock := &MockDetectionEngine{ctrl: ctrl}
	mock.recorder = &MockDetectionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetectionEngine) EXPECT() *MockDetectionEngineMockRecorder {
	return m.recorder
}

// ApplyFilters mocks base method.
func (m *MockDetectionEngine) ApplyFilters(arg0 *model.Detection) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyFilters", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyFilters indicates an expected call of ApplyFilters.
func (mr *MockDetectionEngineMockRecorder) ApplyFilters(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyFilters", reflect.TypeOf((*MockDetectionEngine)(nil).ApplyFilters), arg0)
}

// ConvertRule mocks base method.
func (m *MockDetectionEngine) ConvertRule(arg0 context.Context, arg1 *model.Detection) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRule", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRule indicates an expected call of ConvertRule.
func (mr *MockDetectionEngineMockRecorder) ConvertRule(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRule", reflect.TypeOf((*MockDetectionEngine)(nil).ConvertRule), arg0, arg1)
}

// DuplicateDetection mocks base method.
func (m *MockDetectionEngine) DuplicateDetection(arg0 context.Context, arg1 *model.Detection) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DuplicateDetection", arg0, arg1)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DuplicateDetection indicates an expected call of DuplicateDetection.
func (mr *MockDetectionEngineMockRecorder) DuplicateDetection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DuplicateDetection", reflect.TypeOf((*MockDetectionEngine)(nil).DuplicateDetection), arg0, arg1)
}

// ExtractDetails mocks base method.
func (m *MockDetectionEngine) ExtractDetails(arg0 *model.Detection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractDetails", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractDetails indicates an expected call of ExtractDetails.
func (mr *MockDetectionEngineMockRecorder) ExtractDetails(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractDetails", reflect.TypeOf((*MockDetectionEngine)(nil).ExtractDetails), arg0)
}

// GenerateUnusedPublicId mocks base method.
func (m *MockDetectionEngine) GenerateUnusedPublicId(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUnusedPublicId", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUnusedPublicId indicates an expected call of GenerateUnusedPublicId.
func (mr *MockDetectionEngineMockRecorder) GenerateUnusedPublicId(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUnusedPublicId", reflect.TypeOf((*MockDetectionEngine)(nil).GenerateUnusedPublicId), arg0)
}

// GetState mocks base method.
func (m *MockDetectionEngine) GetState() *model.EngineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(*model.EngineState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockDetectionEngineMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockDetectionEngine)(nil).GetState))
}

// InterruptSync mocks base method.
func (m *MockDetectionEngine) InterruptSync(arg0, arg1 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InterruptSync", arg0, arg1)
}

// InterruptSync indicates an expected call of InterruptSync.
func (mr *MockDetectionEngineMockRecorder) InterruptSync(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterruptSync", reflect.TypeOf((*MockDetectionEngine)(nil).InterruptSync), arg0, arg1)
}

// MergeAuxiliaryData mocks base method.
func (m *MockDetectionEngine) MergeAuxiliaryData(arg0 *model.Detection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeAuxiliaryData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeAuxiliaryData indicates an expected call of MergeAuxiliaryData.
func (mr *MockDetectionEngineMockRecorder) MergeAuxiliaryData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeAuxiliaryData", reflect.TypeOf((*MockDetectionEngine)(nil).MergeAuxiliaryData), arg0)
}

// SyncLocalDetections mocks base method.
func (m *MockDetectionEngine) SyncLocalDetections(arg0 context.Context, arg1 []*model.Detection) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncLocalDetections", arg0, arg1)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncLocalDetections indicates an expected call of SyncLocalDetections.
func (mr *MockDetectionEngineMockRecorder) SyncLocalDetections(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLocalDetections", reflect.TypeOf((*MockDetectionEngine)(nil).SyncLocalDetections), arg0, arg1)
}

// ValidateRule mocks base method.
func (m *MockDetectionEngine) ValidateRule(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRule", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRule indicates an expected call of ValidateRule.
func (mr *MockDetectionEngineMockRecorder) ValidateRule(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRule", reflect.TypeOf((*MockDetectionEngine)(nil).ValidateRule), arg0)
}
