// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Detectionstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_detectionstore.go -package mock . Detectionstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	log "github.com/apex/log"
	esutil "github.com/elastic/go-elasticsearch/v8/esutil"
	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDetectionstore is a mock of Detectionstore interface.
type MockDetectionstore struct {
	ctrl     *gomock.Controller
	recorder *MockDetectionstoreMockRecorder
	isgomock struct{}
}

// MockDetectionstoreMockRecorder is the mock recorder for MockDetectionstore.
type MockDetectionstoreMockRecorder struct {
	mock *MockDetectionstore
}

// NewMockDetectionstore creates a new mock instance.
func NewMockDetectionstore(ctrl *gomock.Controller) *MockDetectionstore {
	mock := &MockDetectionstore{ctrl: ctrl}
	mock.recorder = &MockDetectionstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetectionstore) EXPECT() *MockDetectionstoreMockRecorder {
	return m.recorder
}

// BuildBulkIndexer mocks base method.
func (m *MockDetectionstore) BuildBulkIndexer(ctx context.Context, logger log.Interface) (esutil.BulkIndexer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBulkIndexer", ctx, logger)
	ret0, _ := ret[0].(esutil.BulkIndexer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBulkIndexer indicates an expected call of BuildBulkIndexer.
func (mr *MockDetectionstoreMockRecorder) BuildBulkIndexer(ctx, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBulkIndexer", reflect.TypeOf((*MockDetectionstore)(nil).BuildBulkIndexer), ctx, logger)
}

// BulkAddOverrides mocks base method.
func (m *MockDetectionstore) BulkAddOverrides(ctx context.Context, newOverrides []*model.Override, detects []*model.Detection, logger log.Interface) (*model.BulkUpdateStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAddOverrides", ctx, newOverrides, detects, logger)
	ret0, _ := ret[0].(*model.BulkUpdateStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAddOverrides indicates an expected call of BulkAddOverrides.
func (mr *MockDetectionstoreMockRecorder) BulkAddOverrides(ctx, newOverrides, detects, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAddOverrides", reflect.TypeOf((*MockDetectionstore)(nil).BulkAddOverrides), ctx, newOverrides, detects, logger)
}

// BulkUpdateDetections mocks base method.
func (m *MockDetectionstore) BulkUpdateDetections(ctx context.Context, newStatus bool, detects []*model.Detection, logger log.Interface) (*model.BulkUpdateStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateDetections", ctx, newStatus, detects, logger)
	ret0, _ := ret[0].(*model.BulkUpdateStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpdateDetections indicates an expected call of BulkUpdateDetections.
func (mr *MockDetectionstoreMockRecorder) BulkUpdateDetections(ctx, newStatus, detects, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateDetections", reflect.TypeOf((*MockDetectionstore)(nil).BulkUpdateDetections), ctx, newStatus, detects, logger)
}

// ConvertEventsToDetections mocks base method.
func (m *MockDetectionstore) ConvertEventsToDetections(ctx context.Context, detectEvents *model.EventSearchResults) ([]*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertEventsToDetections", ctx, detectEvents)
	ret0, _ := ret[0].([]*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertEventsToDetections indicates an expected call of ConvertEventsToDetections.
func (mr *MockDetectionstoreMockRecorder) ConvertEventsToDetections(ctx, detectEvents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertEventsToDetections", reflect.TypeOf((*MockDetectionstore)(nil).ConvertEventsToDetections), ctx, detectEvents)
}

// ConvertObjectToDocument mocks base method.
func (m *MockDetectionstore) ConvertObjectToDocument(ctx context.Context, kind string, obj any, auditable *model.Auditable, isEdit bool, auditDocId, op *string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertObjectToDocument", ctx, kind, obj, auditable, isEdit, auditDocId, op)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ConvertObjectToDocument indicates an expected call of ConvertObjectToDocument.
func (mr *MockDetectionstoreMockRecorder) ConvertObjectToDocument(ctx, kind, obj, auditable, isEdit, auditDocId, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertObjectToDocument", reflect.TypeOf((*MockDetectionstore)(nil).ConvertObjectToDocument), ctx, kind, obj, auditable, isEdit, auditDocId, op)
}

// CreateComment mocks base method.
func (m *MockDetectionstore) CreateComment(ctx context.Context, newComment *model.DetectionComment) (*model.DetectionComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, newComment)
	ret0, _ := ret[0].(*model.DetectionComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockDetectionstoreMockRecorder) CreateComment(ctx, newComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockDetectionstore)(nil).CreateComment), ctx, newComment)
}

// CreateDetection mocks base method.
func (m *MockDetectionstore) CreateDetection(ctx context.Context, detect *model.Detection) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDetection", ctx, detect)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDetection indicates an expected call of CreateDetection.
func (mr *MockDetectionstoreMockRecorder) CreateDetection(ctx, detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDetection", reflect.TypeOf((*MockDetectionstore)(nil).CreateDetection), ctx, detect)
}

// DeleteComment mocks base method.
func (m *MockDetectionstore) DeleteComment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockDetectionstoreMockRecorder) DeleteComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockDetectionstore)(nil).DeleteComment), ctx, id)
}

// DeleteDetection mocks base method.
func (m *MockDetectionstore) DeleteDetection(ctx context.Context, detectID string) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDetection", ctx, detectID)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDetection indicates an expected call of DeleteDetection.
func (mr *MockDetectionstoreMockRecorder) DeleteDetection(ctx, detectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDetection", reflect.TypeOf((*MockDetectionstore)(nil).DeleteDetection), ctx, detectID)
}

// DoesTemplateExist mocks base method.
func (m *MockDetectionstore) DoesTemplateExist(ctx context.Context, tmpl string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesTemplateExist", ctx, tmpl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoesTemplateExist indicates an expected call of DoesTemplateExist.
func (mr *MockDetectionstoreMockRecorder) DoesTemplateExist(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesTemplateExist", reflect.TypeOf((*MockDetectionstore)(nil).DoesTemplateExist), ctx, tmpl)
}

// GetAllDetections mocks base method.
func (m *MockDetectionstore) GetAllDetections(ctx context.Context, opts ...model.GetAllOption) (map[string]*model.Detection, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllDetections", varargs...)
	ret0, _ := ret[0].(map[string]*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDetections indicates an expected call of GetAllDetections.
func (mr *MockDetectionstoreMockRecorder) GetAllDetections(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDetections", reflect.TypeOf((*MockDetectionstore)(nil).GetAllDetections), varargs...)
}

// GetComment mocks base method.
func (m *MockDetectionstore) GetComment(ctx context.Context, commentId string) (*model.DetectionComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, commentId)
	ret0, _ := ret[0].(*model.DetectionComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockDetectionstoreMockRecorder) GetComment(ctx, commentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockDetectionstore)(nil).GetComment), ctx, commentId)
}

// GetComments mocks base method.
func (m *MockDetectionstore) GetComments(ctx context.Context, detectionId string) ([]*model.DetectionComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", ctx, detectionId)
	ret0, _ := ret[0].([]*model.DetectionComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockDetectionstoreMockRecorder) GetComments(ctx, detectionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockDetectionstore)(nil).GetComments), ctx, detectionId)
}

// GetDetection mocks base method.
func (m *MockDetectionstore) GetDetection(ctx context.Context, detectId string) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetection", ctx, detectId)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetection indicates an expected call of GetDetection.
func (mr *MockDetectionstoreMockRecorder) GetDetection(ctx, detectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetection", reflect.TypeOf((*MockDetectionstore)(nil).GetDetection), ctx, detectId)
}

// GetDetectionByPublicId mocks base method.
func (m *MockDetectionstore) GetDetectionByPublicId(ctx context.Context, publicId string) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetectionByPublicId", ctx, publicId)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetectionByPublicId indicates an expected call of GetDetectionByPublicId.
func (mr *MockDetectionstoreMockRecorder) GetDetectionByPublicId(ctx, publicId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetectionByPublicId", reflect.TypeOf((*MockDetectionstore)(nil).GetDetectionByPublicId), ctx, publicId)
}

// GetDetectionHistory mocks base method.
func (m *MockDetectionstore) GetDetectionHistory(ctx context.Context, detectID string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetectionHistory", ctx, detectID)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetectionHistory indicates an expected call of GetDetectionHistory.
func (mr *MockDetectionstoreMockRecorder) GetDetectionHistory(ctx, detectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetectionHistory", reflect.TypeOf((*MockDetectionstore)(nil).GetDetectionHistory), ctx, detectID)
}

// Query mocks base method.
func (m *MockDetectionstore) Query(ctx context.Context, query string, max int) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, query, max)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDetectionstoreMockRecorder) Query(ctx, query, max any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDetectionstore)(nil).Query), ctx, query, max)
}

// QueryWithRange mocks base method.
func (m *MockDetectionstore) QueryWithRange(ctx context.Context, query, rangeStart, rangeEnd, rangeFormat string, limit int) (*model.EventSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithRange", ctx, query, rangeStart, rangeEnd, rangeFormat, limit)
	ret0, _ := ret[0].(*model.EventSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithRange indicates an expected call of QueryWithRange.
func (mr *MockDetectionstoreMockRecorder) QueryWithRange(ctx, query, rangeStart, rangeEnd, rangeFormat, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithRange", reflect.TypeOf((*MockDetectionstore)(nil).QueryWithRange), ctx, query, rangeStart, rangeEnd, rangeFormat, limit)
}

// UpdateComment mocks base method.
func (m *MockDetectionstore) UpdateComment(ctx context.Context, comment *model.DetectionComment) (*model.DetectionComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, comment)
	ret0, _ := ret[0].(*model.DetectionComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockDetectionstoreMockRecorder) UpdateComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockDetectionstore)(nil).UpdateComment), ctx, comment)
}

// UpdateDetection mocks base method.
func (m *MockDetectionstore) UpdateDetection(ctx context.Context, detect *model.Detection) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDetection", ctx, detect)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDetection indicates an expected call of UpdateDetection.
func (mr *MockDetectionstoreMockRecorder) UpdateDetection(ctx, detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDetection", reflect.TypeOf((*MockDetectionstore)(nil).UpdateDetection), ctx, detect)
}
