// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Assistantstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_assistantstore.go -package mock . Assistantstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistantstore is a mock of Assistantstore interface.
type MockAssistantstore struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantstoreMockRecorder
	isgomock struct{}
}

// MockAssistantstoreMockRecorder is the mock recorder for MockAssistantstore.
type MockAssistantstoreMockRecorder struct {
	mock *MockAssistantstore
}

// NewMockAssistantstore creates a new mock instance.
func NewMockAssistantstore(ctrl *gomock.Controller) *MockAssistantstore {
	mock := &MockAssistantstore{ctrl: ctrl}
	mock.recorder = &MockAssistantstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantstore) EXPECT() *MockAssistantstoreMockRecorder {
	return m.recorder
}

// GetChatHistory mocks base method.
func (m *MockAssistantstore) GetChatHistory(ctx context.Context, conversationId string) ([]*model.StoredMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", ctx, conversationId)
	ret0, _ := ret[0].([]*model.StoredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockAssistantstoreMockRecorder) GetChatHistory(ctx, conversationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockAssistantstore)(nil).GetChatHistory), ctx, conversationId)
}

// GetPreviousConversations mocks base method.
func (m *MockAssistantstore) GetPreviousConversations(ctx context.Context) ([]*model.StoredMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousConversations", ctx)
	ret0, _ := ret[0].([]*model.StoredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousConversations indicates an expected call of GetPreviousConversations.
func (mr *MockAssistantstoreMockRecorder) GetPreviousConversations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousConversations", reflect.TypeOf((*MockAssistantstore)(nil).GetPreviousConversations), ctx)
}

// SaveChat mocks base method.
func (m *MockAssistantstore) SaveChat(ctx context.Context, chat *model.StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChat", ctx, chat)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChat indicates an expected call of SaveChat.
func (mr *MockAssistantstoreMockRecorder) SaveChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChat", reflect.TypeOf((*MockAssistantstore)(nil).SaveChat), ctx, chat)
}
