// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AlertTriageUpdater)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_alerttriageupdater.go -package mock . AlertTriageUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertTriageUpdater is a mock of AlertTriageUpdater interface.
type MockAlertTriageUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockAlertTriageUpdaterMockRecorder
	isgomock struct{}
}

// MockAlertTriageUpdaterMockRecorder is the mock recorder for MockAlertTriageUpdater.
type MockAlertTriageUpdaterMockRecorder struct {
	mock *MockAlertTriageUpdater
}

// NewMockAlertTriageUpdater creates a new mock instance.
func NewMockAlertTriageUpdater(ctrl *gomock.Controller) *MockAlertTriageUpdater {
	mock := &MockAlertTriageUpdater{ctrl: ctrl}
	mock.recorder = &MockAlertTriageUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertTriageUpdater) EXPECT() *MockAlertTriageUpdaterMockRecorder {
	return m.recorder
}

// AlertTriageSchemaPrefix mocks base method.
func (m *MockAlertTriageUpdater) AlertTriageSchemaPrefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertTriageSchemaPrefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// AlertTriageSchemaPrefix indicates an expected call of AlertTriageSchemaPrefix.
func (mr *MockAlertTriageUpdaterMockRecorder) AlertTriageSchemaPrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertTriageSchemaPrefix", reflect.TypeOf((*MockAlertTriageUpdater)(nil).AlertTriageSchemaPrefix))
}

// AlertTriageUpdate mocks base method.
func (m *MockAlertTriageUpdater) AlertTriageUpdate(ctx context.Context, update *model.AlertTriageUpdate) (*model.EventUpdateResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertTriageUpdate", ctx, update)
	ret0, _ := ret[0].(*model.EventUpdateResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlertTriageUpdate indicates an expected call of AlertTriageUpdate.
func (mr *MockAlertTriageUpdaterMockRecorder) AlertTriageUpdate(ctx, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertTriageUpdate", reflect.TypeOf((*MockAlertTriageUpdater)(nil).AlertTriageUpdate), ctx, update)
}
