// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Casestore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_casestore.go -package mock . Casestore
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCasestore is a mock of Casestore interface.
type MockCasestore struct {
	ctrl     *gomock.Controller
	recorder *MockCasestoreMockRecorder
}

// MockCasestoreMockRecorder is the mock recorder for MockCasestore.
type MockCasestoreMockRecorder struct {
	mock *MockCasestore
}

// NewMockCasestore creates a new mock instance.
func NewMockCasestore(ctrl *gomock.Controller) *MockCasestore {
	mock := &MockCasestore{ctrl: ctrl}
	mock.recorder = &MockCasestoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCasestore) EXPECT() *MockCasestoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCasestore) Create(arg0 context.Context, arg1 *model.Case) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCasestoreMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCasestore)(nil).Create), arg0, arg1)
}

// CreateArtifact mocks base method.
func (m *MockCasestore) CreateArtifact(arg0 context.Context, arg1 *model.Artifact) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtifact", arg0, arg1)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtifact indicates an expected call of CreateArtifact.
func (mr *MockCasestoreMockRecorder) CreateArtifact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtifact", reflect.TypeOf((*MockCasestore)(nil).CreateArtifact), arg0, arg1)
}

// CreateArtifactStream mocks base method.
func (m *MockCasestore) CreateArtifactStream(arg0 context.Context, arg1 *model.ArtifactStream) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtifactStream", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtifactStream indicates an expected call of CreateArtifactStream.
func (mr *MockCasestoreMockRecorder) CreateArtifactStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtifactStream", reflect.TypeOf((*MockCasestore)(nil).CreateArtifactStream), arg0, arg1)
}

// CreateComment mocks base method.
func (m *MockCasestore) CreateComment(arg0 context.Context, arg1 *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCasestoreMockRecorder) CreateComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCasestore)(nil).CreateComment), arg0, arg1)
}

// CreateRelatedEvent mocks base method.
func (m *MockCasestore) CreateRelatedEvent(arg0 context.Context, arg1 *model.RelatedEvent) (*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelatedEvent", arg0, arg1)
	ret0, _ := ret[0].(*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRelatedEvent indicates an expected call of CreateRelatedEvent.
func (mr *MockCasestoreMockRecorder) CreateRelatedEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).CreateRelatedEvent), arg0, arg1)
}

// DeleteArtifact mocks base method.
func (m *MockCasestore) DeleteArtifact(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtifact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtifact indicates an expected call of DeleteArtifact.
func (mr *MockCasestoreMockRecorder) DeleteArtifact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtifact", reflect.TypeOf((*MockCasestore)(nil).DeleteArtifact), arg0, arg1)
}

// DeleteArtifactStream mocks base method.
func (m *MockCasestore) DeleteArtifactStream(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtifactStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtifactStream indicates an expected call of DeleteArtifactStream.
func (mr *MockCasestoreMockRecorder) DeleteArtifactStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtifactStream", reflect.TypeOf((*MockCasestore)(nil).DeleteArtifactStream), arg0, arg1)
}

// DeleteComment mocks base method.
func (m *MockCasestore) DeleteComment(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCasestoreMockRecorder) DeleteComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCasestore)(nil).DeleteComment), arg0, arg1)
}

// DeleteRelatedEvent mocks base method.
func (m *MockCasestore) DeleteRelatedEvent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelatedEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelatedEvent indicates an expected call of DeleteRelatedEvent.
func (mr *MockCasestoreMockRecorder) DeleteRelatedEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).DeleteRelatedEvent), arg0, arg1)
}

// GetArtifact mocks base method.
func (m *MockCasestore) GetArtifact(arg0 context.Context, arg1 string) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifact", arg0, arg1)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifact indicates an expected call of GetArtifact.
func (mr *MockCasestoreMockRecorder) GetArtifact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifact", reflect.TypeOf((*MockCasestore)(nil).GetArtifact), arg0, arg1)
}

// GetArtifactStream mocks base method.
func (m *MockCasestore) GetArtifactStream(arg0 context.Context, arg1 string) (*model.ArtifactStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifactStream", arg0, arg1)
	ret0, _ := ret[0].(*model.ArtifactStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifactStream indicates an expected call of GetArtifactStream.
func (mr *MockCasestoreMockRecorder) GetArtifactStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifactStream", reflect.TypeOf((*MockCasestore)(nil).GetArtifactStream), arg0, arg1)
}

// GetArtifacts mocks base method.
func (m *MockCasestore) GetArtifacts(arg0 context.Context, arg1, arg2, arg3 string) ([]*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifacts", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifacts indicates an expected call of GetArtifacts.
func (mr *MockCasestoreMockRecorder) GetArtifacts(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifacts", reflect.TypeOf((*MockCasestore)(nil).GetArtifacts), arg0, arg1, arg2, arg3)
}

// GetCase mocks base method.
func (m *MockCasestore) GetCase(arg0 context.Context, arg1 string) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCase", arg0, arg1)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCase indicates an expected call of GetCase.
func (mr *MockCasestoreMockRecorder) GetCase(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCase", reflect.TypeOf((*MockCasestore)(nil).GetCase), arg0, arg1)
}

// GetCaseHistory mocks base method.
func (m *MockCasestore) GetCaseHistory(arg0 context.Context, arg1 string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseHistory", arg0, arg1)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseHistory indicates an expected call of GetCaseHistory.
func (mr *MockCasestoreMockRecorder) GetCaseHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseHistory", reflect.TypeOf((*MockCasestore)(nil).GetCaseHistory), arg0, arg1)
}

// GetComment mocks base method.
func (m *MockCasestore) GetComment(arg0 context.Context, arg1 string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", arg0, arg1)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCasestoreMockRecorder) GetComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCasestore)(nil).GetComment), arg0, arg1)
}

// GetComments mocks base method.
func (m *MockCasestore) GetComments(arg0 context.Context, arg1 string) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", arg0, arg1)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockCasestoreMockRecorder) GetComments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockCasestore)(nil).GetComments), arg0, arg1)
}

// GetRelatedEvent mocks base method.
func (m *MockCasestore) GetRelatedEvent(arg0 context.Context, arg1 string) (*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedEvent", arg0, arg1)
	ret0, _ := ret[0].(*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedEvent indicates an expected call of GetRelatedEvent.
func (mr *MockCasestoreMockRecorder) GetRelatedEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).GetRelatedEvent), arg0, arg1)
}

// GetRelatedEvents mocks base method.
func (m *MockCasestore) GetRelatedEvents(arg0 context.Context, arg1 string) ([]*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedEvents", arg0, arg1)
	ret0, _ := ret[0].([]*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedEvents indicates an expected call of GetRelatedEvents.
func (mr *MockCasestoreMockRecorder) GetRelatedEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedEvents", reflect.TypeOf((*MockCasestore)(nil).GetRelatedEvents), arg0, arg1)
}

// Update mocks base method.
func (m *MockCasestore) Update(arg0 context.Context, arg1 *model.Case) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCasestoreMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCasestore)(nil).Update), arg0, arg1)
}

// UpdateArtifact mocks base method.
func (m *MockCasestore) UpdateArtifact(arg0 context.Context, arg1 *model.Artifact) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArtifact", arg0, arg1)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArtifact indicates an expected call of UpdateArtifact.
func (mr *MockCasestoreMockRecorder) UpdateArtifact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArtifact", reflect.TypeOf((*MockCasestore)(nil).UpdateArtifact), arg0, arg1)
}

// UpdateComment mocks base method.
func (m *MockCasestore) UpdateComment(arg0 context.Context, arg1 *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", arg0, arg1)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCasestoreMockRecorder) UpdateComment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCasestore)(nil).UpdateComment), arg0, arg1)
}
