// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Playbookstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_playbookstore.go -package mock . Playbookstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaybookstore is a mock of Playbookstore interface.
type MockPlaybookstore struct {
	ctrl     *gomock.Controller
	recorder *MockPlaybookstoreMockRecorder
	isgomock struct{}
}

// MockPlaybookstoreMockRecorder is the mock recorder for MockPlaybookstore.
type MockPlaybookstoreMockRecorder struct {
	mock *MockPlaybookstore
}

// NewMockPlaybookstore creates a new mock instance.
func NewMockPlaybookstore(ctrl *gomock.Controller) *MockPlaybookstore {
	mock := &MockPlaybookstore{ctrl: ctrl}
	mock.recorder = &MockPlaybookstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaybookstore) EXPECT() *MockPlaybookstoreMockRecorder {
	return m.recorder
}

// ConvertQuestions mocks base method.
func (m *MockPlaybookstore) ConvertQuestions(ctx context.Context, queries []string) ([]*model.ConvertedQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertQuestions", ctx, queries)
	ret0, _ := ret[0].([]*model.ConvertedQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertQuestions indicates an expected call of ConvertQuestions.
func (mr *MockPlaybookstoreMockRecorder) ConvertQuestions(ctx, queries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertQuestions", reflect.TypeOf((*MockPlaybookstore)(nil).ConvertQuestions), ctx, queries)
}

// ExecutePlaybookSearches mocks base method.
func (m *MockPlaybookstore) ExecutePlaybookSearches(ctx context.Context, event *model.EventRecord, pbs []*model.Playbook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePlaybookSearches", ctx, event, pbs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePlaybookSearches indicates an expected call of ExecutePlaybookSearches.
func (mr *MockPlaybookstoreMockRecorder) ExecutePlaybookSearches(ctx, event, pbs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePlaybookSearches", reflect.TypeOf((*MockPlaybookstore)(nil).ExecutePlaybookSearches), ctx, event, pbs)
}

// GetEventSpecificPlaybook mocks base method.
func (m *MockPlaybookstore) GetEventSpecificPlaybook(ctx context.Context, id string) ([]*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventSpecificPlaybook", ctx, id)
	ret0, _ := ret[0].([]*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventSpecificPlaybook indicates an expected call of GetEventSpecificPlaybook.
func (mr *MockPlaybookstoreMockRecorder) GetEventSpecificPlaybook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventSpecificPlaybook", reflect.TypeOf((*MockPlaybookstore)(nil).GetEventSpecificPlaybook), ctx, id)
}

// GetPlaybookById mocks base method.
func (m *MockPlaybookstore) GetPlaybookById(ctx context.Context, id string) (*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookById", ctx, id)
	ret0, _ := ret[0].(*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookById indicates an expected call of GetPlaybookById.
func (mr *MockPlaybookstoreMockRecorder) GetPlaybookById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookById", reflect.TypeOf((*MockPlaybookstore)(nil).GetPlaybookById), ctx, id)
}

// GetPlaybooksForDetection mocks base method.
func (m *MockPlaybookstore) GetPlaybooksForDetection(ctx context.Context, detectId, detectCategory string, detectEngine model.EngineName) ([]*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksForDetection", ctx, detectId, detectCategory, detectEngine)
	ret0, _ := ret[0].([]*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksForDetection indicates an expected call of GetPlaybooksForDetection.
func (mr *MockPlaybookstoreMockRecorder) GetPlaybooksForDetection(ctx, detectId, detectCategory, detectEngine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksForDetection", reflect.TypeOf((*MockPlaybookstore)(nil).GetPlaybooksForDetection), ctx, detectId, detectCategory, detectEngine)
}

// GetPlaybooksForDetectionGrouped mocks base method.
func (m *MockPlaybookstore) GetPlaybooksForDetectionGrouped(ctx context.Context, detectId, detectCategory string, detectEngine model.EngineName) (*model.GroupedPlaybooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksForDetectionGrouped", ctx, detectId, detectCategory, detectEngine)
	ret0, _ := ret[0].(*model.GroupedPlaybooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksForDetectionGrouped indicates an expected call of GetPlaybooksForDetectionGrouped.
func (mr *MockPlaybookstoreMockRecorder) GetPlaybooksForDetectionGrouped(ctx, detectId, detectCategory, detectEngine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksForDetectionGrouped", reflect.TypeOf((*MockPlaybookstore)(nil).GetPlaybooksForDetectionGrouped), ctx, detectId, detectCategory, detectEngine)
}

// Interrupt mocks base method.
func (m *MockPlaybookstore) Interrupt(ctx context.Context, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Interrupt", ctx, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Interrupt indicates an expected call of Interrupt.
func (mr *MockPlaybookstoreMockRecorder) Interrupt(ctx, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interrupt", reflect.TypeOf((*MockPlaybookstore)(nil).Interrupt), ctx, force)
}

// CreatePlaybook mocks base method.
func (m *MockPlaybookstore) CreatePlaybook(ctx context.Context, playbook *model.Playbook) (*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybook", ctx, playbook)
	ret0, _ := ret[0].(*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybook indicates an expected call of CreatePlaybook.
func (mr *MockPlaybookstoreMockRecorder) CreatePlaybook(ctx, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybook", reflect.TypeOf((*MockPlaybookstore)(nil).CreatePlaybook), ctx, playbook)
}

// UpdatePlaybook mocks base method.
func (m *MockPlaybookstore) UpdatePlaybook(ctx context.Context, playbook *model.Playbook) (*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybook", ctx, playbook)
	ret0, _ := ret[0].(*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybook indicates an expected call of UpdatePlaybook.
func (mr *MockPlaybookstoreMockRecorder) UpdatePlaybook(ctx, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybook", reflect.TypeOf((*MockPlaybookstore)(nil).UpdatePlaybook), ctx, playbook)
}

// DeletePlaybook mocks base method.
func (m *MockPlaybookstore) DeletePlaybook(ctx context.Context, playbookId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaybook", ctx, playbookId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaybook indicates an expected call of DeletePlaybook.
func (mr *MockPlaybookstoreMockRecorder) DeletePlaybook(ctx, playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaybook", reflect.TypeOf((*MockPlaybookstore)(nil).DeletePlaybook), ctx, playbookId)
}

// GetAllPlaybooks mocks base method.
func (m *MockPlaybookstore) GetAllPlaybooks(ctx context.Context) ([]*model.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlaybooks", ctx)
	ret0, _ := ret[0].([]*model.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPlaybooks indicates an expected call of GetAllPlaybooks.
func (mr *MockPlaybookstoreMockRecorder) GetAllPlaybooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlaybooks", reflect.TypeOf((*MockPlaybookstore)(nil).GetAllPlaybooks), ctx)
}
