// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Casestore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_casestore.go -package mock . Casestore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	log "github.com/apex/log"
	esutil "github.com/elastic/go-elasticsearch/v8/esutil"
	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCasestore is a mock of Casestore interface.
type MockCasestore struct {
	ctrl     *gomock.Controller
	recorder *MockCasestoreMockRecorder
	isgomock struct{}
}

// MockCasestoreMockRecorder is the mock recorder for MockCasestore.
type MockCasestoreMockRecorder struct {
	mock *MockCasestore
}

// NewMockCasestore creates a new mock instance.
func NewMockCasestore(ctrl *gomock.Controller) *MockCasestore {
	mock := &MockCasestore{ctrl: ctrl}
	mock.recorder = &MockCasestoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCasestore) EXPECT() *MockCasestoreMockRecorder {
	return m.recorder
}

// BuildBulkIndexer mocks base method.
func (m *MockCasestore) BuildBulkIndexer(ctx context.Context, logger log.Interface) (esutil.BulkIndexer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBulkIndexer", ctx, logger)
	ret0, _ := ret[0].(esutil.BulkIndexer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBulkIndexer indicates an expected call of BuildBulkIndexer.
func (mr *MockCasestoreMockRecorder) BuildBulkIndexer(ctx, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBulkIndexer", reflect.TypeOf((*MockCasestore)(nil).BuildBulkIndexer), ctx, logger)
}

// ConvertObjectToDocument mocks base method.
func (m *MockCasestore) ConvertObjectToDocument(ctx context.Context, kind string, obj any, auditable *model.Auditable, isEdit bool, auditDocId, op *string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertObjectToDocument", ctx, kind, obj, auditable, isEdit, auditDocId, op)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ConvertObjectToDocument indicates an expected call of ConvertObjectToDocument.
func (mr *MockCasestoreMockRecorder) ConvertObjectToDocument(ctx, kind, obj, auditable, isEdit, auditDocId, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertObjectToDocument", reflect.TypeOf((*MockCasestore)(nil).ConvertObjectToDocument), ctx, kind, obj, auditable, isEdit, auditDocId, op)
}

// Create mocks base method.
func (m *MockCasestore) Create(ctx context.Context, newCase *model.Case) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, newCase)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCasestoreMockRecorder) Create(ctx, newCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCasestore)(nil).Create), ctx, newCase)
}

// CreateArtifact mocks base method.
func (m *MockCasestore) CreateArtifact(ctx context.Context, artifact *model.Artifact) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtifact", ctx, artifact)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtifact indicates an expected call of CreateArtifact.
func (mr *MockCasestoreMockRecorder) CreateArtifact(ctx, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtifact", reflect.TypeOf((*MockCasestore)(nil).CreateArtifact), ctx, artifact)
}

// CreateArtifactStream mocks base method.
func (m *MockCasestore) CreateArtifactStream(ctx context.Context, artifactstream *model.ArtifactStream) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtifactStream", ctx, artifactstream)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtifactStream indicates an expected call of CreateArtifactStream.
func (mr *MockCasestoreMockRecorder) CreateArtifactStream(ctx, artifactstream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtifactStream", reflect.TypeOf((*MockCasestore)(nil).CreateArtifactStream), ctx, artifactstream)
}

// CreateComment mocks base method.
func (m *MockCasestore) CreateComment(ctx context.Context, newComment *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, newComment)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCasestoreMockRecorder) CreateComment(ctx, newComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCasestore)(nil).CreateComment), ctx, newComment)
}

// CreateRelatedEvents mocks base method.
func (m *MockCasestore) CreateRelatedEvents(ctx context.Context, events []*model.RelatedEvent) (int, map[string]error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelatedEvents", ctx, events)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRelatedEvents indicates an expected call of CreateRelatedEvents.
func (mr *MockCasestoreMockRecorder) CreateRelatedEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelatedEvents", reflect.TypeOf((*MockCasestore)(nil).CreateRelatedEvents), ctx, events)
}

// DeleteArtifact mocks base method.
func (m *MockCasestore) DeleteArtifact(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtifact", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtifact indicates an expected call of DeleteArtifact.
func (mr *MockCasestoreMockRecorder) DeleteArtifact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtifact", reflect.TypeOf((*MockCasestore)(nil).DeleteArtifact), ctx, id)
}

// DeleteArtifactStream mocks base method.
func (m *MockCasestore) DeleteArtifactStream(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtifactStream", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtifactStream indicates an expected call of DeleteArtifactStream.
func (mr *MockCasestoreMockRecorder) DeleteArtifactStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtifactStream", reflect.TypeOf((*MockCasestore)(nil).DeleteArtifactStream), ctx, id)
}

// DeleteComment mocks base method.
func (m *MockCasestore) DeleteComment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCasestoreMockRecorder) DeleteComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCasestore)(nil).DeleteComment), ctx, id)
}

// DeleteRelatedEvent mocks base method.
func (m *MockCasestore) DeleteRelatedEvent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelatedEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelatedEvent indicates an expected call of DeleteRelatedEvent.
func (mr *MockCasestoreMockRecorder) DeleteRelatedEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).DeleteRelatedEvent), ctx, id)
}

// GetArtifact mocks base method.
func (m *MockCasestore) GetArtifact(ctx context.Context, id string) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifact", ctx, id)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifact indicates an expected call of GetArtifact.
func (mr *MockCasestoreMockRecorder) GetArtifact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifact", reflect.TypeOf((*MockCasestore)(nil).GetArtifact), ctx, id)
}

// GetArtifactStream mocks base method.
func (m *MockCasestore) GetArtifactStream(ctx context.Context, id string) (*model.ArtifactStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifactStream", ctx, id)
	ret0, _ := ret[0].(*model.ArtifactStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifactStream indicates an expected call of GetArtifactStream.
func (mr *MockCasestoreMockRecorder) GetArtifactStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifactStream", reflect.TypeOf((*MockCasestore)(nil).GetArtifactStream), ctx, id)
}

// GetArtifacts mocks base method.
func (m *MockCasestore) GetArtifacts(ctx context.Context, caseId, groupType, groupId string) ([]*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifacts", ctx, caseId, groupType, groupId)
	ret0, _ := ret[0].([]*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifacts indicates an expected call of GetArtifacts.
func (mr *MockCasestoreMockRecorder) GetArtifacts(ctx, caseId, groupType, groupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifacts", reflect.TypeOf((*MockCasestore)(nil).GetArtifacts), ctx, caseId, groupType, groupId)
}

// GetCase mocks base method.
func (m *MockCasestore) GetCase(ctx context.Context, caseId string) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCase", ctx, caseId)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCase indicates an expected call of GetCase.
func (mr *MockCasestoreMockRecorder) GetCase(ctx, caseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCase", reflect.TypeOf((*MockCasestore)(nil).GetCase), ctx, caseId)
}

// GetCaseHistory mocks base method.
func (m *MockCasestore) GetCaseHistory(ctx context.Context, caseId string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseHistory", ctx, caseId)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseHistory indicates an expected call of GetCaseHistory.
func (mr *MockCasestoreMockRecorder) GetCaseHistory(ctx, caseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseHistory", reflect.TypeOf((*MockCasestore)(nil).GetCaseHistory), ctx, caseId)
}

// GetCaseIdsWithArtifact mocks base method.
func (m *MockCasestore) GetCaseIdsWithArtifact(ctx context.Context, artType, value string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseIdsWithArtifact", ctx, artType, value)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseIdsWithArtifact indicates an expected call of GetCaseIdsWithArtifact.
func (mr *MockCasestoreMockRecorder) GetCaseIdsWithArtifact(ctx, artType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseIdsWithArtifact", reflect.TypeOf((*MockCasestore)(nil).GetCaseIdsWithArtifact), ctx, artType, value)
}

// GetComment mocks base method.
func (m *MockCasestore) GetComment(ctx context.Context, commentId string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, commentId)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCasestoreMockRecorder) GetComment(ctx, commentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCasestore)(nil).GetComment), ctx, commentId)
}

// GetComments mocks base method.
func (m *MockCasestore) GetComments(ctx context.Context, caseId string) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", ctx, caseId)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockCasestoreMockRecorder) GetComments(ctx, caseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockCasestore)(nil).GetComments), ctx, caseId)
}

// GetRelatedEvent mocks base method.
func (m *MockCasestore) GetRelatedEvent(ctx context.Context, id string) (*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedEvent", ctx, id)
	ret0, _ := ret[0].(*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedEvent indicates an expected call of GetRelatedEvent.
func (mr *MockCasestoreMockRecorder) GetRelatedEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).GetRelatedEvent), ctx, id)
}

// GetRelatedEvents mocks base method.
func (m *MockCasestore) GetRelatedEvents(ctx context.Context, caseId string) ([]*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedEvents", ctx, caseId)
	ret0, _ := ret[0].([]*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedEvents indicates an expected call of GetRelatedEvents.
func (mr *MockCasestoreMockRecorder) GetRelatedEvents(ctx, caseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedEvents", reflect.TypeOf((*MockCasestore)(nil).GetRelatedEvents), ctx, caseId)
}

// UpdateRelatedEvent mocks base method.
func (m *MockCasestore) UpdateRelatedEvent(ctx context.Context, event *model.RelatedEvent) (*model.RelatedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelatedEvent", ctx, event)
	ret0, _ := ret[0].(*model.RelatedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRelatedEvent indicates an expected call of UpdateRelatedEvent.
func (mr *MockCasestoreMockRecorder) UpdateRelatedEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelatedEvent", reflect.TypeOf((*MockCasestore)(nil).UpdateRelatedEvent), ctx, event)
}

// Update mocks base method.
func (m *MockCasestore) Update(ctx context.Context, socCase *model.Case) (*model.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, socCase)
	ret0, _ := ret[0].(*model.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCasestoreMockRecorder) Update(ctx, socCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCasestore)(nil).Update), ctx, socCase)
}

// UpdateArtifact mocks base method.
func (m *MockCasestore) UpdateArtifact(ctx context.Context, artifact *model.Artifact) (*model.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArtifact", ctx, artifact)
	ret0, _ := ret[0].(*model.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArtifact indicates an expected call of UpdateArtifact.
func (mr *MockCasestoreMockRecorder) UpdateArtifact(ctx, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArtifact", reflect.TypeOf((*MockCasestore)(nil).UpdateArtifact), ctx, artifact)
}

// UpdateComment mocks base method.
func (m *MockCasestore) UpdateComment(ctx context.Context, comment *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, comment)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCasestoreMockRecorder) UpdateComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCasestore)(nil).UpdateComment), ctx, comment)
}
