// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AdminUserstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_adminuserstore.go -package mock . AdminUserstore
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserstore is a mock of AdminUserstore interface.
type MockAdminUserstore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserstoreMockRecorder
}

// MockAdminUserstoreMockRecorder is the mock recorder for MockAdminUserstore.
type MockAdminUserstoreMockRecorder struct {
	mock *MockAdminUserstore
}

// NewMockAdminUserstore creates a new mock instance.
func NewMockAdminUserstore(ctrl *gomock.Controller) *MockAdminUserstore {
	mock := &MockAdminUserstore{ctrl: ctrl}
	mock.recorder = &MockAdminUserstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserstore) EXPECT() *MockAdminUserstoreMockRecorder {
	return m.recorder
}

// AddRole mocks base method.
func (m *MockAdminUserstore) AddRole(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRole", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRole indicates an expected call of AddRole.
func (mr *MockAdminUserstoreMockRecorder) AddRole(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRole", reflect.TypeOf((*MockAdminUserstore)(nil).AddRole), arg0, arg1, arg2)
}

// AddUser mocks base method.
func (m *MockAdminUserstore) AddUser(arg0 context.Context, arg1 *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockAdminUserstoreMockRecorder) AddUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockAdminUserstore)(nil).AddUser), arg0, arg1)
}

// DeleteRole mocks base method.
func (m *MockAdminUserstore) DeleteRole(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAdminUserstoreMockRecorder) DeleteRole(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAdminUserstore)(nil).DeleteRole), arg0, arg1, arg2)
}

// DeleteUser mocks base method.
func (m *MockAdminUserstore) DeleteUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAdminUserstoreMockRecorder) DeleteUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAdminUserstore)(nil).DeleteUser), arg0, arg1)
}

// DisableUser mocks base method.
func (m *MockAdminUserstore) DisableUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableUser indicates an expected call of DisableUser.
func (mr *MockAdminUserstoreMockRecorder) DisableUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUser", reflect.TypeOf((*MockAdminUserstore)(nil).DisableUser), arg0, arg1)
}

// EnableUser mocks base method.
func (m *MockAdminUserstore) EnableUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableUser indicates an expected call of EnableUser.
func (mr *MockAdminUserstoreMockRecorder) EnableUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableUser", reflect.TypeOf((*MockAdminUserstore)(nil).EnableUser), arg0, arg1)
}

// ResetPassword mocks base method.
func (m *MockAdminUserstore) ResetPassword(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAdminUserstoreMockRecorder) ResetPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAdminUserstore)(nil).ResetPassword), arg0, arg1, arg2)
}

// SyncUsers mocks base method.
func (m *MockAdminUserstore) SyncUsers(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUsers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUsers indicates an expected call of SyncUsers.
func (mr *MockAdminUserstoreMockRecorder) SyncUsers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUsers", reflect.TypeOf((*MockAdminUserstore)(nil).SyncUsers), arg0)
}

// UpdateProfile mocks base method.
func (m *MockAdminUserstore) UpdateProfile(arg0 context.Context, arg1 *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAdminUserstoreMockRecorder) UpdateProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAdminUserstore)(nil).UpdateProfile), arg0, arg1)
}
