// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: DetectionEngine)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_detectionengine.go -package mock . DetectionEngine
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDetectionEngine is a mock of DetectionEngine interface.
type MockDetectionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDetectionEngineMockRecorder
	isgomock struct{}
}

// MockDetectionEngineMockRecorder is the mock recorder for MockDetectionEngine.
type MockDetectionEngineMockRecorder struct {
	mock *MockDetectionEngine
}

// NewMockDetectionEngine creates a new mock instance.
func NewMockDetectionEngine(ctrl *gomock.Controller) *MockDetectionEngine {
	mock := &MockDetectionEngine{ctrl: ctrl}
	mock.recorder = &MockDetectionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetectionEngine) EXPECT() *MockDetectionEngineMockRecorder {
	return m.recorder
}

// ApplyFilters mocks base method.
func (m *MockDetectionEngine) ApplyFilters(detect *model.Detection) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyFilters", detect)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyFilters indicates an expected call of ApplyFilters.
func (mr *MockDetectionEngineMockRecorder) ApplyFilters(detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyFilters", reflect.TypeOf((*MockDetectionEngine)(nil).ApplyFilters), detect)
}

// ConvertRule mocks base method.
func (m *MockDetectionEngine) ConvertRule(ctx context.Context, detect *model.Detection) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRule", ctx, detect)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRule indicates an expected call of ConvertRule.
func (mr *MockDetectionEngineMockRecorder) ConvertRule(ctx, detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRule", reflect.TypeOf((*MockDetectionEngine)(nil).ConvertRule), ctx, detect)
}

// DuplicateDetection mocks base method.
func (m *MockDetectionEngine) DuplicateDetection(ctx context.Context, detection *model.Detection) (*model.Detection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DuplicateDetection", ctx, detection)
	ret0, _ := ret[0].(*model.Detection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DuplicateDetection indicates an expected call of DuplicateDetection.
func (mr *MockDetectionEngineMockRecorder) DuplicateDetection(ctx, detection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DuplicateDetection", reflect.TypeOf((*MockDetectionEngine)(nil).DuplicateDetection), ctx, detection)
}

// ExtractDetails mocks base method.
func (m *MockDetectionEngine) ExtractDetails(detect *model.Detection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractDetails", detect)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractDetails indicates an expected call of ExtractDetails.
func (mr *MockDetectionEngineMockRecorder) ExtractDetails(detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractDetails", reflect.TypeOf((*MockDetectionEngine)(nil).ExtractDetails), detect)
}

// GenerateUnusedPublicId mocks base method.
func (m *MockDetectionEngine) GenerateUnusedPublicId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUnusedPublicId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUnusedPublicId indicates an expected call of GenerateUnusedPublicId.
func (mr *MockDetectionEngineMockRecorder) GenerateUnusedPublicId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUnusedPublicId", reflect.TypeOf((*MockDetectionEngine)(nil).GenerateUnusedPublicId), ctx)
}

// GetState mocks base method.
func (m *MockDetectionEngine) GetState() *model.EngineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(*model.EngineState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockDetectionEngineMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockDetectionEngine)(nil).GetState))
}

// InterruptSync mocks base method.
func (m *MockDetectionEngine) InterruptSync(forceFull, notify bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InterruptSync", forceFull, notify)
}

// InterruptSync indicates an expected call of InterruptSync.
func (mr *MockDetectionEngineMockRecorder) InterruptSync(forceFull, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterruptSync", reflect.TypeOf((*MockDetectionEngine)(nil).InterruptSync), forceFull, notify)
}

// MergeAuxiliaryData mocks base method.
func (m *MockDetectionEngine) MergeAuxiliaryData(detect *model.Detection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeAuxiliaryData", detect)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeAuxiliaryData indicates an expected call of MergeAuxiliaryData.
func (mr *MockDetectionEngineMockRecorder) MergeAuxiliaryData(detect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeAuxiliaryData", reflect.TypeOf((*MockDetectionEngine)(nil).MergeAuxiliaryData), detect)
}

// SyncLocalDetections mocks base method.
func (m *MockDetectionEngine) SyncLocalDetections(ctx context.Context, detections []*model.Detection) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncLocalDetections", ctx, detections)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncLocalDetections indicates an expected call of SyncLocalDetections.
func (mr *MockDetectionEngineMockRecorder) SyncLocalDetections(ctx, detections any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLocalDetections", reflect.TypeOf((*MockDetectionEngine)(nil).SyncLocalDetections), ctx, detections)
}

// ValidateRule mocks base method.
func (m *MockDetectionEngine) ValidateRule(rule string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRule", rule)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRule indicates an expected call of ValidateRule.
func (mr *MockDetectionEngineMockRecorder) ValidateRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRule", reflect.TypeOf((*MockDetectionEngine)(nil).ValidateRule), rule)
}
