// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AdminClientstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_adminclientstore.go -package mock . AdminClientstore
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminClientstore is a mock of AdminClientstore interface.
type MockAdminClientstore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminClientstoreMockRecorder
}

// MockAdminClientstoreMockRecorder is the mock recorder for MockAdminClientstore.
type MockAdminClientstoreMockRecorder struct {
	mock *MockAdminClientstore
}

// NewMockAdminClientstore creates a new mock instance.
func NewMockAdminClientstore(ctrl *gomock.Controller) *MockAdminClientstore {
	mock := &MockAdminClientstore{ctrl: ctrl}
	mock.recorder = &MockAdminClientstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminClientstore) EXPECT() *MockAdminClientstoreMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockAdminClientstore) AddClient(arg0 context.Context, arg1 *model.Client) (*model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", arg0, arg1)
	ret0, _ := ret[0].(*model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddClient indicates an expected call of AddClient.
func (mr *MockAdminClientstoreMockRecorder) AddClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockAdminClientstore)(nil).AddClient), arg0, arg1)
}

// AddClientPermission mocks base method.
func (m *MockAdminClientstore) AddClientPermission(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClientPermission", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClientPermission indicates an expected call of AddClientPermission.
func (mr *MockAdminClientstoreMockRecorder) AddClientPermission(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClientPermission", reflect.TypeOf((*MockAdminClientstore)(nil).AddClientPermission), arg0, arg1, arg2)
}

// DeleteClient mocks base method.
func (m *MockAdminClientstore) DeleteClient(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockAdminClientstoreMockRecorder) DeleteClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockAdminClientstore)(nil).DeleteClient), arg0, arg1)
}

// DeleteClientPermission mocks base method.
func (m *MockAdminClientstore) DeleteClientPermission(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClientPermission", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClientPermission indicates an expected call of DeleteClientPermission.
func (mr *MockAdminClientstoreMockRecorder) DeleteClientPermission(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClientPermission", reflect.TypeOf((*MockAdminClientstore)(nil).DeleteClientPermission), arg0, arg1, arg2)
}

// GenerateSecret mocks base method.
func (m *MockAdminClientstore) GenerateSecret(arg0 context.Context, arg1 string) (*model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecret", arg0, arg1)
	ret0, _ := ret[0].(*model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecret indicates an expected call of GenerateSecret.
func (mr *MockAdminClientstoreMockRecorder) GenerateSecret(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecret", reflect.TypeOf((*MockAdminClientstore)(nil).GenerateSecret), arg0, arg1)
}

// UpdateClient mocks base method.
func (m *MockAdminClientstore) UpdateClient(arg0 context.Context, arg1 *model.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockAdminClientstoreMockRecorder) UpdateClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockAdminClientstore)(nil).UpdateClient), arg0, arg1)
}
