// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AdminUserstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_adminuserstore.go -package mock . AdminUserstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserstore is a mock of AdminUserstore interface.
type MockAdminUserstore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserstoreMockRecorder
	isgomock struct{}
}

// MockAdminUserstoreMockRecorder is the mock recorder for MockAdminUserstore.
type MockAdminUserstoreMockRecorder struct {
	mock *MockAdminUserstore
}

// NewMockAdminUserstore creates a new mock instance.
func NewMockAdminUserstore(ctrl *gomock.Controller) *MockAdminUserstore {
	mock := &MockAdminUserstore{ctrl: ctrl}
	mock.recorder = &MockAdminUserstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserstore) EXPECT() *MockAdminUserstoreMockRecorder {
	return m.recorder
}

// AddRole mocks base method.
func (m *MockAdminUserstore) AddRole(ctx context.Context, id, role string, bypassAuthCheck bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRole", ctx, id, role, bypassAuthCheck)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRole indicates an expected call of AddRole.
func (mr *MockAdminUserstoreMockRecorder) AddRole(ctx, id, role, bypassAuthCheck any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRole", reflect.TypeOf((*MockAdminUserstore)(nil).AddRole), ctx, id, role, bypassAuthCheck)
}

// AddUser mocks base method.
func (m *MockAdminUserstore) AddUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockAdminUserstoreMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockAdminUserstore)(nil).AddUser), ctx, user)
}

// DeleteRole mocks base method.
func (m *MockAdminUserstore) DeleteRole(ctx context.Context, id, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAdminUserstoreMockRecorder) DeleteRole(ctx, id, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAdminUserstore)(nil).DeleteRole), ctx, id, role)
}

// DeleteUser mocks base method.
func (m *MockAdminUserstore) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAdminUserstoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAdminUserstore)(nil).DeleteUser), ctx, id)
}

// DisableUser mocks base method.
func (m *MockAdminUserstore) DisableUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableUser indicates an expected call of DisableUser.
func (mr *MockAdminUserstoreMockRecorder) DisableUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUser", reflect.TypeOf((*MockAdminUserstore)(nil).DisableUser), ctx, id)
}

// EnableUser mocks base method.
func (m *MockAdminUserstore) EnableUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableUser indicates an expected call of EnableUser.
func (mr *MockAdminUserstoreMockRecorder) EnableUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableUser", reflect.TypeOf((*MockAdminUserstore)(nil).EnableUser), ctx, id)
}

// ResetPassword mocks base method.
func (m *MockAdminUserstore) ResetPassword(ctx context.Context, id, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, id, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAdminUserstoreMockRecorder) ResetPassword(ctx, id, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAdminUserstore)(nil).ResetPassword), ctx, id, password)
}

// SyncUsers mocks base method.
func (m *MockAdminUserstore) SyncUsers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUsers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUsers indicates an expected call of SyncUsers.
func (mr *MockAdminUserstoreMockRecorder) SyncUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUsers", reflect.TypeOf((*MockAdminUserstore)(nil).SyncUsers), ctx)
}

// UpdateProfile mocks base method.
func (m *MockAdminUserstore) UpdateProfile(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAdminUserstoreMockRecorder) UpdateProfile(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAdminUserstore)(nil).UpdateProfile), ctx, user)
}
