// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AssistantManager)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_assistantmanager.go -package mock . AssistantManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistantManager is a mock of AssistantManager interface.
type MockAssistantManager struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantManagerMockRecorder
	isgomock struct{}
}

// MockAssistantManagerMockRecorder is the mock recorder for MockAssistantManager.
type MockAssistantManagerMockRecorder struct {
	mock *MockAssistantManager
}

// NewMockAssistantManager creates a new mock instance.
func NewMockAssistantManager(ctrl *gomock.Controller) *MockAssistantManager {
	mock := &MockAssistantManager{ctrl: ctrl}
	mock.recorder = &MockAssistantManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantManager) EXPECT() *MockAssistantManagerMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *MockAssistantManager) Balance(ctx context.Context, aiModel string) (*model.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", ctx, aiModel)
	ret0, _ := ret[0].(*model.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockAssistantManagerMockRecorder) Balance(ctx, aiModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockAssistantManager)(nil).Balance), ctx, aiModel)
}

// Chat mocks base method.
func (m *MockAssistantManager) Chat(ctx context.Context, aiModel string, messages []*model.Message, opts ...model.ChatOpt) ([]*model.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, aiModel, messages}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Chat", varargs...)
	ret0, _ := ret[0].([]*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockAssistantManagerMockRecorder) Chat(ctx, aiModel, messages any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, aiModel, messages}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockAssistantManager)(nil).Chat), varargs...)
}

// ChatStream mocks base method.
func (m *MockAssistantManager) ChatStream(ctx context.Context, aiModel string, messages []*model.Message) (*http.Response, *model.AuxMessageData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, aiModel, messages)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(*model.AuxMessageData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockAssistantManagerMockRecorder) ChatStream(ctx, aiModel, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockAssistantManager)(nil).ChatStream), ctx, aiModel, messages)
}

// ExecuteTool mocks base method.
func (m *MockAssistantManager) ExecuteTool(ctx context.Context, toolName, params, auxData string) (*model.ToolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTool", ctx, toolName, params, auxData)
	ret0, _ := ret[0].(*model.ToolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTool indicates an expected call of ExecuteTool.
func (mr *MockAssistantManagerMockRecorder) ExecuteTool(ctx, toolName, params, auxData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTool", reflect.TypeOf((*MockAssistantManager)(nil).ExecuteTool), ctx, toolName, params, auxData)
}

// Health mocks base method.
func (m *MockAssistantManager) Health(ctx context.Context, aiModel string) (*model.HealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx, aiModel)
	ret0, _ := ret[0].(*model.HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockAssistantManagerMockRecorder) Health(ctx, aiModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockAssistantManager)(nil).Health), ctx, aiModel)
}
