// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Assistantstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_assistantstore.go -package mock . Assistantstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistantstore is a mock of Assistantstore interface.
type MockAssistantstore struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantstoreMockRecorder
	isgomock struct{}
}

// MockAssistantstoreMockRecorder is the mock recorder for MockAssistantstore.
type MockAssistantstoreMockRecorder struct {
	mock *MockAssistantstore
}

// NewMockAssistantstore creates a new mock instance.
func NewMockAssistantstore(ctrl *gomock.Controller) *MockAssistantstore {
	mock := &MockAssistantstore{ctrl: ctrl}
	mock.recorder = &MockAssistantstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantstore) EXPECT() *MockAssistantstoreMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockAssistantstore) CreateSession(ctx context.Context, session *model.AssistantSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAssistantstoreMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAssistantstore)(nil).CreateSession), ctx, session)
}

// DeleteSession mocks base method.
func (m *MockAssistantstore) DeleteSession(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockAssistantstoreMockRecorder) DeleteSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockAssistantstore)(nil).DeleteSession), arg0, arg1)
}

// GetChatHistory mocks base method.
func (m *MockAssistantstore) GetChatHistory(arg0 context.Context, arg1 string) ([]*model.StoredMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", arg0, arg1)
	ret0, _ := ret[0].([]*model.StoredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockAssistantstoreMockRecorder) GetChatHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockAssistantstore)(nil).GetChatHistory), arg0, arg1)
}

// GetSessions mocks base method.
func (m *MockAssistantstore) GetSessions(ctx context.Context, userId string) ([]*model.AssistantSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", ctx, userId)
	ret0, _ := ret[0].([]*model.AssistantSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockAssistantstoreMockRecorder) GetSessions(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockAssistantstore)(nil).GetSessions), ctx, userId)
}

// SaveChat mocks base method.
func (m *MockAssistantstore) SaveChat(arg0 context.Context, arg1 *model.StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChat", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChat indicates an expected call of SaveChat.
func (mr *MockAssistantstoreMockRecorder) SaveChat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChat", reflect.TypeOf((*MockAssistantstore)(nil).SaveChat), arg0, arg1)
}
