// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Schedulestore)

package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSchedulestore is a mock of Schedulestore interface.
type MockSchedulestore struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulestoreMockRecorder
	isgomock struct{}
}

// MockSchedulestoreMockRecorder is the mock recorder for MockSchedulestore.
type MockSchedulestoreMockRecorder struct {
	mock *MockSchedulestore
}

// NewMockSchedulestore creates a new mock instance.
func NewMockSchedulestore(ctrl *gomock.Controller) *MockSchedulestore {
	mock := &MockSchedulestore{ctrl: ctrl}
	mock.recorder = &MockSchedulestoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulestore) EXPECT() *MockSchedulestoreMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockSchedulestore) CreateSchedule(ctx context.Context, schedule *model.Schedule) (*model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, schedule)
	ret0, _ := ret[0].(*model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockSchedulestoreMockRecorder) CreateSchedule(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockSchedulestore)(nil).CreateSchedule), ctx, schedule)
}

// DeleteSchedule mocks base method.
func (m *MockSchedulestore) DeleteSchedule(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockSchedulestoreMockRecorder) DeleteSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockSchedulestore)(nil).DeleteSchedule), ctx, id)
}

// EvaluateSchedule mocks base method.
func (m *MockSchedulestore) EvaluateSchedule(ctx context.Context, schedule *model.Schedule, evalTime time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateSchedule", ctx, schedule, evalTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateSchedule indicates an expected call of EvaluateSchedule.
func (mr *MockSchedulestoreMockRecorder) EvaluateSchedule(ctx, schedule, evalTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateSchedule", reflect.TypeOf((*MockSchedulestore)(nil).EvaluateSchedule), ctx, schedule, evalTime)
}

// GetSchedule mocks base method.
func (m *MockSchedulestore) GetSchedule(ctx context.Context, id string) (*model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", ctx, id)
	ret0, _ := ret[0].(*model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockSchedulestoreMockRecorder) GetSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockSchedulestore)(nil).GetSchedule), ctx, id)
}

// GetSchedules mocks base method.
func (m *MockSchedulestore) GetSchedules(ctx context.Context) ([]model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedules", ctx)
	ret0, _ := ret[0].([]model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedules indicates an expected call of GetSchedules.
func (mr *MockSchedulestoreMockRecorder) GetSchedules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedules", reflect.TypeOf((*MockSchedulestore)(nil).GetSchedules), ctx)
}

// IsScheduleActive mocks base method.
func (m *MockSchedulestore) IsScheduleActive(ctx context.Context, scheduleID string, evalTime time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsScheduleActive", ctx, scheduleID, evalTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsScheduleActive indicates an expected call of IsScheduleActive.
func (mr *MockSchedulestoreMockRecorder) IsScheduleActive(ctx, scheduleID, evalTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsScheduleActive", reflect.TypeOf((*MockSchedulestore)(nil).IsScheduleActive), ctx, scheduleID, evalTime)
}

// UpdateSchedule mocks base method.
func (m *MockSchedulestore) UpdateSchedule(ctx context.Context, id string, schedule *model.Schedule) (*model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, id, schedule)
	ret0, _ := ret[0].(*model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockSchedulestoreMockRecorder) UpdateSchedule(ctx, id, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockSchedulestore)(nil).UpdateSchedule), ctx, id, schedule)
}
