// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Notificationstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_notificationstore.go -package mock . Notificationstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationstore is a mock of Notificationstore interface.
type MockNotificationstore struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationstoreMockRecorder
	isgomock struct{}
}

// MockNotificationstoreMockRecorder is the mock recorder for MockNotificationstore.
type MockNotificationstoreMockRecorder struct {
	mock *MockNotificationstore
}

// NewMockNotificationstore creates a new mock instance.
func NewMockNotificationstore(ctrl *gomock.Controller) *MockNotificationstore {
	mock := &MockNotificationstore{ctrl: ctrl}
	mock.recorder = &MockNotificationstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationstore) EXPECT() *MockNotificationstoreMockRecorder {
	return m.recorder
}

// GetAuditLogs mocks base method.
func (m *MockNotificationstore) GetAuditLogs(ctx context.Context, id string) ([]*model.NotificationAuditEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogs", ctx, id)
	ret0, _ := ret[0].([]*model.NotificationAuditEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogs indicates an expected call of GetAuditLogs.
func (mr *MockNotificationstoreMockRecorder) GetAuditLogs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogs", reflect.TypeOf((*MockNotificationstore)(nil).GetAuditLogs), ctx, id)
}

// GetLastUnreadTime mocks base method.
func (m *MockNotificationstore) GetLastUnreadTime(ctx context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUnreadTime", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUnreadTime indicates an expected call of GetLastUnreadTime.
func (mr *MockNotificationstoreMockRecorder) GetLastUnreadTime(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUnreadTime", reflect.TypeOf((*MockNotificationstore)(nil).GetLastUnreadTime), ctx)
}

// GetNotifications mocks base method.
func (m *MockNotificationstore) GetNotifications(ctx context.Context, filter string, limit ...int) (*model.NotificationListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, filter}
	for _, a := range limit {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNotifications", varargs...)
	ret0, _ := ret[0].(*model.NotificationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotifications indicates an expected call of GetNotifications.
func (mr *MockNotificationstoreMockRecorder) GetNotifications(ctx, filter any, limit ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, filter}, limit...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifications", reflect.TypeOf((*MockNotificationstore)(nil).GetNotifications), varargs...)
}

// SetAllDismissed mocks base method.
func (m *MockNotificationstore) SetAllDismissed(ctx context.Context, isDismissed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllDismissed", ctx, isDismissed)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllDismissed indicates an expected call of SetAllDismissed.
func (mr *MockNotificationstoreMockRecorder) SetAllDismissed(ctx, isDismissed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllDismissed", reflect.TypeOf((*MockNotificationstore)(nil).SetAllDismissed), ctx, isDismissed)
}

// SetDismissed mocks base method.
func (m *MockNotificationstore) SetDismissed(ctx context.Context, id string, isDismissed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDismissed", ctx, id, isDismissed)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDismissed indicates an expected call of SetDismissed.
func (mr *MockNotificationstoreMockRecorder) SetDismissed(ctx, id, isDismissed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDismissed", reflect.TypeOf((*MockNotificationstore)(nil).SetDismissed), ctx, id, isDismissed)
}

// SetAllRead mocks base method.
func (m *MockNotificationstore) SetAllRead(ctx context.Context, isRead bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllRead", ctx, isRead)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllRead indicates an expected call of SetAllRead.
func (mr *MockNotificationstoreMockRecorder) SetAllRead(ctx, isRead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllRead", reflect.TypeOf((*MockNotificationstore)(nil).SetAllRead), ctx, isRead)
}

// SetRead mocks base method.
func (m *MockNotificationstore) SetRead(ctx context.Context, id string, isRead bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRead", ctx, id, isRead)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRead indicates an expected call of SetRead.
func (mr *MockNotificationstoreMockRecorder) SetRead(ctx, id, isRead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRead", reflect.TypeOf((*MockNotificationstore)(nil).SetRead), ctx, id, isRead)
}
