// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Clientstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_clientstore.go -package mock . Clientstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClientstore is a mock of Clientstore interface.
type MockClientstore struct {
	ctrl     *gomock.Controller
	recorder *MockClientstoreMockRecorder
	isgomock struct{}
}

// MockClientstoreMockRecorder is the mock recorder for MockClientstore.
type MockClientstoreMockRecorder struct {
	mock *MockClientstore
}

// NewMockClientstore creates a new mock instance.
func NewMockClientstore(ctrl *gomock.Controller) *MockClientstore {
	mock := &MockClientstore{ctrl: ctrl}
	mock.recorder = &MockClientstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientstore) EXPECT() *MockClientstoreMockRecorder {
	return m.recorder
}

// GetClientById mocks base method.
func (m *MockClientstore) GetClientById(ctx context.Context, id string) (*model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientById", ctx, id)
	ret0, _ := ret[0].(*model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientById indicates an expected call of GetClientById.
func (mr *MockClientstoreMockRecorder) GetClientById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientById", reflect.TypeOf((*MockClientstore)(nil).GetClientById), ctx, id)
}

// GetClientByToken mocks base method.
func (m *MockClientstore) GetClientByToken(ctx context.Context, token string) (*model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByToken", ctx, token)
	ret0, _ := ret[0].(*model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByToken indicates an expected call of GetClientByToken.
func (mr *MockClientstoreMockRecorder) GetClientByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByToken", reflect.TypeOf((*MockClientstore)(nil).GetClientByToken), ctx, token)
}

// GetClients mocks base method.
func (m *MockClientstore) GetClients(ctx context.Context) ([]*model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients", ctx)
	ret0, _ := ret[0].([]*model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClients indicates an expected call of GetClients.
func (mr *MockClientstoreMockRecorder) GetClients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockClientstore)(nil).GetClients), ctx)
}
