// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: GridMembersstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_gridmembersstore.go -package mock . GridMembersstore
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGridMembersstore is a mock of GridMembersstore interface.
type MockGridMembersstore struct {
	ctrl     *gomock.Controller
	recorder *MockGridMembersstoreMockRecorder
}

// MockGridMembersstoreMockRecorder is the mock recorder for MockGridMembersstore.
type MockGridMembersstoreMockRecorder struct {
	mock *MockGridMembersstore
}

// NewMockGridMembersstore creates a new mock instance.
func NewMockGridMembersstore(ctrl *gomock.Controller) *MockGridMembersstore {
	mock := &MockGridMembersstore{ctrl: ctrl}
	mock.recorder = &MockGridMembersstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGridMembersstore) EXPECT() *MockGridMembersstoreMockRecorder {
	return m.recorder
}

// GetMembers mocks base method.
func (m *MockGridMembersstore) GetMembers(arg0 context.Context) ([]*model.GridMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", arg0)
	ret0, _ := ret[0].([]*model.GridMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockGridMembersstoreMockRecorder) GetMembers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockGridMembersstore)(nil).GetMembers), arg0)
}

// Import mocks base method.
func (m *MockGridMembersstore) Import(arg0 context.Context, arg1, arg2, arg3 string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockGridMembersstoreMockRecorder) Import(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockGridMembersstore)(nil).Import), arg0, arg1, arg2, arg3)
}

// ManageMember mocks base method.
func (m *MockGridMembersstore) ManageMember(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManageMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ManageMember indicates an expected call of ManageMember.
func (mr *MockGridMembersstoreMockRecorder) ManageMember(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManageMember", reflect.TypeOf((*MockGridMembersstore)(nil).ManageMember), arg0, arg1, arg2)
}

// SendFile mocks base method.
func (m *MockGridMembersstore) SendFile(arg0 context.Context, arg1, arg2, arg3 string, arg4 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFile indicates an expected call of SendFile.
func (mr *MockGridMembersstoreMockRecorder) SendFile(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockGridMembersstore)(nil).SendFile), arg0, arg1, arg2, arg3, arg4)
}
