// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: AssistantManager)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_assistantmanager.go -package mock . AssistantManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistantManager is a mock of AssistantManager interface.
type MockAssistantManager struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantManagerMockRecorder
	isgomock struct{}
}

// MockAssistantManagerMockRecorder is the mock recorder for MockAssistantManager.
type MockAssistantManagerMockRecorder struct {
	mock *MockAssistantManager
}

// NewMockAssistantManager creates a new mock instance.
func NewMockAssistantManager(ctrl *gomock.Controller) *MockAssistantManager {
	mock := &MockAssistantManager{ctrl: ctrl}
	mock.recorder = &MockAssistantManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantManager) EXPECT() *MockAssistantManagerMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *MockAssistantManager) Balance(arg0 context.Context) (*model.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", arg0)
	ret0, _ := ret[0].(*model.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockAssistantManagerMockRecorder) Balance(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockAssistantManager)(nil).Balance), arg0)
}

// Chat mocks base method.
func (m *MockAssistantManager) Chat(arg0 context.Context, arg1 []*model.ChatMessage) (*model.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", arg0, arg1)
	ret0, _ := ret[0].(*model.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockAssistantManagerMockRecorder) Chat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockAssistantManager)(nil).Chat), arg0, arg1)
}

// ChatStream mocks base method.
func (m *MockAssistantManager) ChatStream(ctx context.Context, messages []*model.ChatMessage) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, messages)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockAssistantManagerMockRecorder) ChatStream(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockAssistantManager)(nil).ChatStream), ctx, messages)
}

// ExecuteTool mocks base method.
func (m *MockAssistantManager) ExecuteTool(ctx context.Context, toolName, params string) (*model.ToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTool", ctx, toolName, params)
	ret0, _ := ret[0].(*model.ToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTool indicates an expected call of ExecuteTool.
func (mr *MockAssistantManagerMockRecorder) ExecuteTool(ctx, toolName, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTool", reflect.TypeOf((*MockAssistantManager)(nil).ExecuteTool), ctx, toolName, params)
}
