// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server (interfaces: Assistantstore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_assistantstore.go -package mock . Assistantstore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistantstore is a mock of Assistantstore interface.
type MockAssistantstore struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantstoreMockRecorder
	isgomock struct{}
}

// MockAssistantstoreMockRecorder is the mock recorder for MockAssistantstore.
type MockAssistantstoreMockRecorder struct {
	mock *MockAssistantstore
}

// NewMockAssistantstore creates a new mock instance.
func NewMockAssistantstore(ctrl *gomock.Controller) *MockAssistantstore {
	mock := &MockAssistantstore{ctrl: ctrl}
	mock.recorder = &MockAssistantstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantstore) EXPECT() *MockAssistantstoreMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockAssistantstore) CreateSession(arg0 context.Context, arg1 *model.AssistantSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAssistantstoreMockRecorder) CreateSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAssistantstore)(nil).CreateSession), arg0, arg1)
}

// DeleteSession mocks base method.
func (m *MockAssistantstore) DeleteSession(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockAssistantstoreMockRecorder) DeleteSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockAssistantstore)(nil).DeleteSession), arg0, arg1)
}

// GetChatHistory mocks base method.
func (m *MockAssistantstore) GetChatHistory(arg0 context.Context, arg1 string, arg2 bool) ([]*model.StoredMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.StoredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockAssistantstoreMockRecorder) GetChatHistory(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockAssistantstore)(nil).GetChatHistory), arg0, arg1, arg2)
}

// GetSessions mocks base method.
func (m *MockAssistantstore) GetSessions(arg0 context.Context, arg1 bool, arg2 ...model.GetSessionsOpt) ([]*model.AssistantSession, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSessions", varargs...)
	ret0, _ := ret[0].([]*model.AssistantSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockAssistantstoreMockRecorder) GetSessions(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockAssistantstore)(nil).GetSessions), varargs...)
}

// GetUsage mocks base method.
func (m *MockAssistantstore) GetUsage(arg0 context.Context, arg1, arg2 time.Time) ([]*model.UserUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.UserUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockAssistantstoreMockRecorder) GetUsage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockAssistantstore)(nil).GetUsage), arg0, arg1, arg2)
}

// SaveChat mocks base method.
func (m *MockAssistantstore) SaveChat(arg0 context.Context, arg1 *model.StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChat", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChat indicates an expected call of SaveChat.
func (mr *MockAssistantstoreMockRecorder) SaveChat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChat", reflect.TypeOf((*MockAssistantstore)(nil).SaveChat), arg0, arg1)
}
