// Code generated by MockGen. DO NOT EDIT.
// Source: eventstore.go
//
// Generated by this command:
//
//	mockgen -source=eventstore.go -destination=mock/mock_eventstore.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEventstore is a mock of Eventstore interface.
type MockEventstore struct {
	ctrl     *gomock.Controller
	recorder *MockEventstoreMockRecorder
	isgomock struct{}
}

// MockEventstoreMockRecorder is the mock recorder for MockEventstore.
type MockEventstoreMockRecorder struct {
	mock *MockEventstore
}

// NewMockEventstore creates a new mock instance.
func NewMockEventstore(ctrl *gomock.Controller) *MockEventstore {
	mock := &MockEventstore{ctrl: ctrl}
	mock.recorder = &MockEventstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventstore) EXPECT() *MockEventstoreMockRecorder {
	return m.recorder
}

// Acknowledge mocks base method.
func (m *MockEventstore) Acknowledge(arg0 context.Context, criteria *model.EventAckCriteria) (*model.EventUpdateResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acknowledge", arg0, criteria)
	ret0, _ := ret[0].(*model.EventUpdateResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acknowledge indicates an expected call of Acknowledge.
func (mr *MockEventstoreMockRecorder) Acknowledge(arg0, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acknowledge", reflect.TypeOf((*MockEventstore)(nil).Acknowledge), arg0, criteria)
}

// CancelQuery mocks base method.
func (m *MockEventstore) CancelQuery(arg0 context.Context, queryId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelQuery", arg0, queryId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelQuery indicates an expected call of CancelQuery.
func (mr *MockEventstoreMockRecorder) CancelQuery(arg0, queryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelQuery", reflect.TypeOf((*MockEventstore)(nil).CancelQuery), arg0, queryId)
}

// ClusterHealthReport mocks base method.
func (m *MockEventstore) ClusterHealthReport(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterHealthReport", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterHealthReport indicates an expected call of ClusterHealthReport.
func (mr *MockEventstoreMockRecorder) ClusterHealthReport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterHealthReport", reflect.TypeOf((*MockEventstore)(nil).ClusterHealthReport), ctx)
}

// ClusterSettings mocks base method.
func (m *MockEventstore) ClusterSettings(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterSettings", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterSettings indicates an expected call of ClusterSettings.
func (mr *MockEventstoreMockRecorder) ClusterSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterSettings", reflect.TypeOf((*MockEventstore)(nil).ClusterSettings), ctx)
}

// Delete mocks base method.
func (m *MockEventstore) Delete(arg0 context.Context, index, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, index, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventstoreMockRecorder) Delete(arg0, index, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventstore)(nil).Delete), arg0, index, id)
}

// ExplainAllocation mocks base method.
func (m *MockEventstore) ExplainAllocation(ctx context.Context, index string, shard int64, primary bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExplainAllocation", ctx, index, shard, primary)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExplainAllocation indicates an expected call of ExplainAllocation.
func (mr *MockEventstoreMockRecorder) ExplainAllocation(ctx, index, shard, primary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExplainAllocation", reflect.TypeOf((*MockEventstore)(nil).ExplainAllocation), ctx, index, shard, primary)
}

// GetActiveQueries mocks base method.
func (m *MockEventstore) GetActiveQueries(arg0 context.Context, filter bool) ([]*model.QueryTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveQueries", arg0, filter)
	ret0, _ := ret[0].([]*model.QueryTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveQueries indicates an expected call of GetActiveQueries.
func (mr *MockEventstoreMockRecorder) GetActiveQueries(arg0, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveQueries", reflect.TypeOf((*MockEventstore)(nil).GetActiveQueries), arg0, filter)
}

// Index mocks base method.
func (m *MockEventstore) Index(ctx context.Context, index string, document map[string]any, id string) (*model.EventIndexResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, index, document, id)
	ret0, _ := ret[0].(*model.EventIndexResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Index indicates an expected call of Index.
func (mr *MockEventstoreMockRecorder) Index(ctx, index, document, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockEventstore)(nil).Index), ctx, index, document, id)
}

// ListNodes mocks base method.
func (m *MockEventstore) ListNodes(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockEventstoreMockRecorder) ListNodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockEventstore)(nil).ListNodes), ctx)
}

// ListShards mocks base method.
func (m *MockEventstore) ListShards(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShards", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShards indicates an expected call of ListShards.
func (mr *MockEventstoreMockRecorder) ListShards(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShards", reflect.TypeOf((*MockEventstore)(nil).ListShards), ctx)
}

// MSearch mocks base method.
func (m *MockEventstore) MSearch(arg0 context.Context, criteria []*model.EventMSearchCriteria) (*model.EventMSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MSearch", arg0, criteria)
	ret0, _ := ret[0].(*model.EventMSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MSearch indicates an expected call of MSearch.
func (mr *MockEventstoreMockRecorder) MSearch(arg0, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MSearch", reflect.TypeOf((*MockEventstore)(nil).MSearch), arg0, criteria)
}

// Scroll mocks base method.
func (m *MockEventstore) Scroll(arg0 context.Context, criteria *model.EventScrollCriteria, indexes []string) (*model.EventScrollResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scroll", arg0, criteria, indexes)
	ret0, _ := ret[0].(*model.EventScrollResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scroll indicates an expected call of Scroll.
func (mr *MockEventstoreMockRecorder) Scroll(arg0, criteria, indexes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scroll", reflect.TypeOf((*MockEventstore)(nil).Scroll), arg0, criteria, indexes)
}

// Search mocks base method.
func (m *MockEventstore) Search(arg0 context.Context, criteria *model.EventSearchCriteria) (*model.EventSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, criteria)
	ret0, _ := ret[0].(*model.EventSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockEventstoreMockRecorder) Search(arg0, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockEventstore)(nil).Search), arg0, criteria)
}

// Update mocks base method.
func (m *MockEventstore) Update(arg0 context.Context, criteria *model.EventUpdateCriteria) (*model.EventUpdateResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, criteria)
	ret0, _ := ret[0].(*model.EventUpdateResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEventstoreMockRecorder) Update(arg0, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventstore)(nil).Update), arg0, criteria)
}
