// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/security-onion-solutions/securityonion-soc/server/modules/assistant (interfaces: AutomationStore)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_automationstore.go -package mock . AutomationStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	model "github.com/security-onion-solutions/securityonion-soc/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAutomationStore is a mock of AutomationStore interface.
type MockAutomationStore struct {
	ctrl     *gomock.Controller
	recorder *MockAutomationStoreMockRecorder
	isgomock struct{}
}

// MockAutomationStoreMockRecorder is the mock recorder for MockAutomationStore.
type MockAutomationStoreMockRecorder struct {
	mock *MockAutomationStore
}

// NewMockAutomationStore creates a new mock instance.
func NewMockAutomationStore(ctrl *gomock.Controller) *MockAutomationStore {
	mock := &MockAutomationStore{ctrl: ctrl}
	mock.recorder = &MockAutomationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutomationStore) EXPECT() *MockAutomationStoreMockRecorder {
	return m.recorder
}

// ClaimNextAutomationWorkItem mocks base method.
func (m *MockAutomationStore) ClaimNextAutomationWorkItem(ctx context.Context, automationId, runId string, maxFailures int) (*model.AutomationWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextAutomationWorkItem", ctx, automationId, runId, maxFailures)
	ret0, _ := ret[0].(*model.AutomationWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextAutomationWorkItem indicates an expected call of ClaimNextAutomationWorkItem.
func (mr *MockAutomationStoreMockRecorder) ClaimNextAutomationWorkItem(ctx, automationId, runId, maxFailures any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextAutomationWorkItem", reflect.TypeOf((*MockAutomationStore)(nil).ClaimNextAutomationWorkItem), ctx, automationId, runId, maxFailures)
}

// CompleteAutomationWorkItem mocks base method.
func (m *MockAutomationStore) CompleteAutomationWorkItem(ctx context.Context, itemId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteAutomationWorkItem", ctx, itemId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteAutomationWorkItem indicates an expected call of CompleteAutomationWorkItem.
func (mr *MockAutomationStoreMockRecorder) CompleteAutomationWorkItem(ctx, itemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteAutomationWorkItem", reflect.TypeOf((*MockAutomationStore)(nil).CompleteAutomationWorkItem), ctx, itemId)
}

// EnsureAutomationWorkItemSession mocks base method.
func (m *MockAutomationStore) EnsureAutomationWorkItemSession(ctx context.Context, itemId, sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureAutomationWorkItemSession", ctx, itemId, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureAutomationWorkItemSession indicates an expected call of EnsureAutomationWorkItemSession.
func (mr *MockAutomationStoreMockRecorder) EnsureAutomationWorkItemSession(ctx, itemId, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureAutomationWorkItemSession", reflect.TypeOf((*MockAutomationStore)(nil).EnsureAutomationWorkItemSession), ctx, itemId, sessionId)
}

// EnsureAutomationWorkItems mocks base method.
func (m *MockAutomationStore) EnsureAutomationWorkItems(ctx context.Context, runId string, items []*model.AutomationWorkItem) ([]*model.AutomationWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureAutomationWorkItems", ctx, runId, items)
	ret0, _ := ret[0].([]*model.AutomationWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureAutomationWorkItems indicates an expected call of EnsureAutomationWorkItems.
func (mr *MockAutomationStoreMockRecorder) EnsureAutomationWorkItems(ctx, runId, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureAutomationWorkItems", reflect.TypeOf((*MockAutomationStore)(nil).EnsureAutomationWorkItems), ctx, runId, items)
}

// FailAutomationWorkItem mocks base method.
func (m *MockAutomationStore) FailAutomationWorkItem(ctx context.Context, itemId, cause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailAutomationWorkItem", ctx, itemId, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailAutomationWorkItem indicates an expected call of FailAutomationWorkItem.
func (mr *MockAutomationStoreMockRecorder) FailAutomationWorkItem(ctx, itemId, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailAutomationWorkItem", reflect.TypeOf((*MockAutomationStore)(nil).FailAutomationWorkItem), ctx, itemId, cause)
}

// FailAutomationWorkItemRun mocks base method.
func (m *MockAutomationStore) FailAutomationWorkItemRun(ctx context.Context, itemId, cause string) (*model.AutomationWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailAutomationWorkItemRun", ctx, itemId, cause)
	ret0, _ := ret[0].(*model.AutomationWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailAutomationWorkItemRun indicates an expected call of FailAutomationWorkItemRun.
func (mr *MockAutomationStoreMockRecorder) FailAutomationWorkItemRun(ctx, itemId, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailAutomationWorkItemRun", reflect.TypeOf((*MockAutomationStore)(nil).FailAutomationWorkItemRun), ctx, itemId, cause)
}

// ListOpenAutomationWorkItems mocks base method.
func (m *MockAutomationStore) ListOpenAutomationWorkItems(ctx context.Context, automationId string) ([]*model.AutomationWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenAutomationWorkItems", ctx, automationId)
	ret0, _ := ret[0].([]*model.AutomationWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenAutomationWorkItems indicates an expected call of ListOpenAutomationWorkItems.
func (mr *MockAutomationStoreMockRecorder) ListOpenAutomationWorkItems(ctx, automationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenAutomationWorkItems", reflect.TypeOf((*MockAutomationStore)(nil).ListOpenAutomationWorkItems), ctx, automationId)
}

// MarkAutomationWorkItemApplying mocks base method.
func (m *MockAutomationStore) MarkAutomationWorkItemApplying(ctx context.Context, itemId string, result json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAutomationWorkItemApplying", ctx, itemId, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAutomationWorkItemApplying indicates an expected call of MarkAutomationWorkItemApplying.
func (mr *MockAutomationStoreMockRecorder) MarkAutomationWorkItemApplying(ctx, itemId, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAutomationWorkItemApplying", reflect.TypeOf((*MockAutomationStore)(nil).MarkAutomationWorkItemApplying), ctx, itemId, result)
}

// RequeueAutomationWorkItem mocks base method.
func (m *MockAutomationStore) RequeueAutomationWorkItem(ctx context.Context, itemId, cause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueAutomationWorkItem", ctx, itemId, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeueAutomationWorkItem indicates an expected call of RequeueAutomationWorkItem.
func (mr *MockAutomationStoreMockRecorder) RequeueAutomationWorkItem(ctx, itemId, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueAutomationWorkItem", reflect.TypeOf((*MockAutomationStore)(nil).RequeueAutomationWorkItem), ctx, itemId, cause)
}
