// Code generated by MockGen. DO NOT EDIT.
// Source: gemini_client.go
//
// Generated by this command:
//
//	mockgen -source=gemini_client.go -destination=mock/mock_gemini_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	assistant "github.com/security-onion-solutions/securityonion-soc/server/modules/assistant"
	gomock "go.uber.org/mock/gomock"
	genai "google.golang.org/genai"
)

// MockGeminiClient is a mock of GeminiClient interface.
type MockGeminiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiClientMockRecorder
	isgomock struct{}
}

// MockGeminiClientMockRecorder is the mock recorder for MockGeminiClient.
type MockGeminiClientMockRecorder struct {
	mock *MockGeminiClient
}

// NewMockGeminiClient creates a new mock instance.
func NewMockGeminiClient(ctrl *gomock.Controller) *MockGeminiClient {
	mock := &MockGeminiClient{ctrl: ctrl}
	mock.recorder = &MockGeminiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiClient) EXPECT() *MockGeminiClientMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockGeminiClient) CheckHealth(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockGeminiClientMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockGeminiClient)(nil).CheckHealth), ctx)
}

// CreateSession mocks base method.
func (m *MockGeminiClient) CreateSession(ctx context.Context, model string, config *genai.GenerateContentConfig, history []*genai.Content) (assistant.GeminiSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, model, config, history)
	ret0, _ := ret[0].(assistant.GeminiSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockGeminiClientMockRecorder) CreateSession(ctx, model, config, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockGeminiClient)(nil).CreateSession), ctx, model, config, history)
}

// MockGeminiSession is a mock of GeminiSession interface.
type MockGeminiSession struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiSessionMockRecorder
	isgomock struct{}
}

// MockGeminiSessionMockRecorder is the mock recorder for MockGeminiSession.
type MockGeminiSessionMockRecorder struct {
	mock *MockGeminiSession
}

// NewMockGeminiSession creates a new mock instance.
func NewMockGeminiSession(ctrl *gomock.Controller) *MockGeminiSession {
	mock := &MockGeminiSession{ctrl: ctrl}
	mock.recorder = &MockGeminiSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiSession) EXPECT() *MockGeminiSessionMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockGeminiSession) SendMessage(ctx context.Context, part genai.Part) (*genai.GenerateContentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, part)
	ret0, _ := ret[0].(*genai.GenerateContentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockGeminiSessionMockRecorder) SendMessage(ctx, part any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockGeminiSession)(nil).SendMessage), ctx, part)
}

// SendMessageStream mocks base method.
func (m *MockGeminiSession) SendMessageStream(ctx context.Context, part genai.Part) iter.Seq2[*genai.GenerateContentResponse, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageStream", ctx, part)
	ret0, _ := ret[0].(iter.Seq2[*genai.GenerateContentResponse, error])
	return ret0
}

// SendMessageStream indicates an expected call of SendMessageStream.
func (mr *MockGeminiSessionMockRecorder) SendMessageStream(ctx, part any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageStream", reflect.TypeOf((*MockGeminiSession)(nil).SendMessageStream), ctx, part)
}
