// Code generated by MockGen. DO NOT EDIT.
// Source: openai_client.go
//
// Generated by this command:
//
//	mockgen -source=openai_client.go -destination=mock/mock_openai_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	openai "github.com/openai/openai-go/v3"
	pagination "github.com/openai/openai-go/v3/packages/pagination"
	ssestream "github.com/openai/openai-go/v3/packages/ssestream"
	responses "github.com/openai/openai-go/v3/responses"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenAIClient is a mock of OpenAIClient interface.
type MockOpenAIClient struct {
	ctrl     *gomock.Controller
	recorder *MockOpenAIClientMockRecorder
	isgomock struct{}
}

// MockOpenAIClientMockRecorder is the mock recorder for MockOpenAIClient.
type MockOpenAIClientMockRecorder struct {
	mock *MockOpenAIClient
}

// NewMockOpenAIClient creates a new mock instance.
func NewMockOpenAIClient(ctrl *gomock.Controller) *MockOpenAIClient {
	mock := &MockOpenAIClient{ctrl: ctrl}
	mock.recorder = &MockOpenAIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenAIClient) EXPECT() *MockOpenAIClientMockRecorder {
	return m.recorder
}

// ModelsList mocks base method.
func (m *MockOpenAIClient) ModelsList(ctx context.Context) (*pagination.Page[openai.Model], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelsList", ctx)
	ret0, _ := ret[0].(*pagination.Page[openai.Model])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelsList indicates an expected call of ModelsList.
func (mr *MockOpenAIClientMockRecorder) ModelsList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelsList", reflect.TypeOf((*MockOpenAIClient)(nil).ModelsList), ctx)
}

// ResponsesNew mocks base method.
func (m *MockOpenAIClient) ResponsesNew(ctx context.Context, params responses.ResponseNewParams) (*responses.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponsesNew", ctx, params)
	ret0, _ := ret[0].(*responses.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResponsesNew indicates an expected call of ResponsesNew.
func (mr *MockOpenAIClientMockRecorder) ResponsesNew(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesNew", reflect.TypeOf((*MockOpenAIClient)(nil).ResponsesNew), ctx, params)
}

// ResponsesNewStreaming mocks base method.
func (m *MockOpenAIClient) ResponsesNewStreaming(ctx context.Context, params responses.ResponseNewParams) *ssestream.Stream[responses.ResponseStreamEventUnion] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponsesNewStreaming", ctx, params)
	ret0, _ := ret[0].(*ssestream.Stream[responses.ResponseStreamEventUnion])
	return ret0
}

// ResponsesNewStreaming indicates an expected call of ResponsesNewStreaming.
func (mr *MockOpenAIClientMockRecorder) ResponsesNewStreaming(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesNewStreaming", reflect.TypeOf((*MockOpenAIClient)(nil).ResponsesNewStreaming), ctx, params)
}
