// Copyright 2019 Jason Ertel (github.com/jertel).
// Copyright 2020-2025 Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
// or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
// https://securityonion.net/license; you may not use this file except in compliance with the
// Elastic License 2.0.

package server

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/security-onion-solutions/securityonion-soc/model"
	"github.com/security-onion-solutions/securityonion-soc/util"
	"github.com/security-onion-solutions/securityonion-soc/web"

	"github.com/apex/log"
	"github.com/go-chi/chi/v5"
)

type CaseHandler struct {
	server *Server
}

func NewCaseHandler(srv *Server) *CaseHandler {
	return &CaseHandler{
		server: srv,
	}
}

func RegisterCaseRoutes(srv *Server, r chi.Router, prefix string) {
	h := &CaseHandler{
		server: srv,
	}

	r.Route(prefix, func(r chi.Router) {
		r.Use(h.caseEnabled)

		r.Post("/", h.createCase)
		r.Post("/events", h.CreateEvents)
		r.Post("/comments", h.createComment)
		r.Post("/tasks", h.createArtifact)
		r.Post("/artifacts", h.createArtifact)

		r.Get("/comments", h.getComment)
		r.Get("/comments/{id}", h.getComment)
		r.Get("/events", h.getEvent)
		r.Get("/events/{id}", h.getEvent)
		r.Get("/tasks", h.getTask)
		r.Get("/tasks/{id}", h.getTask)
		r.Get("/artifactstream", h.getTask)
		r.Get("/artifactstream/{id}", h.getTask)
		r.Get("/artifacts/{groupType}", h.getArtifact)
		r.Get("/artifacts/{groupType}/{groupID}", h.getArtifact)
		r.Get("/artifacts/{groupType}/{groupID}/{id}", h.getArtifact)
		r.Get("/history", h.getHistory)
		r.Get("/history/{id}", h.getHistory)
		r.Get("/", h.getCase)
		r.Get("/{id}", h.getCase)

		r.Put("/", h.updateCase)
		r.Put("/comments", h.updateComment)
		r.Put("/tasks", h.updateArtifact)
		r.Put("/artifacts", h.updateArtifact)

		r.Delete("/comments", h.deleteComment)
		r.Delete("/comments/{id}", h.deleteComment)
		r.Delete("/events", h.deleteEvent)
		r.Delete("/events/{id}", h.deleteEvent)
		r.Delete("/tasks", h.deleteArtifact)
		r.Delete("/tasks/{id}", h.deleteArtifact)
		r.Delete("/artifacts", h.deleteArtifact)
		r.Delete("/artifacts/{id}", h.deleteArtifact)
	})
}

func (h *CaseHandler) caseEnabled(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if h.server.Casestore == nil {
			web.Respond(w, r, http.StatusMethodNotAllowed, errors.New("ERROR_CASE_MODULE_NOT_ENABLED"))
			return
		}

		next.ServeHTTP(w, r)
	})
}

// @Summary      Create Case
// @Description  Create a new case given a populated case object as input.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Case true "New case object. ID will be generated by the server."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.Case   "Outputs the case object including its generated ID."
// @Failure      400                         "The provided input object or parameters are malformed or invalid"
// @Failure      401                         "Request was not properly authenticated"
// @Failure      403                         "Insufficient permissions for this request"
// @Failure      405                         "Case module not configured on server"
// @Failure      500                         "Internal SOC error; review SOC logs"
// @Router       /connect/case/ [post]
func (h *CaseHandler) createCase(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	inputCase := model.NewCase()

	err := json.NewDecoder(r.Body).Decode(&inputCase)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	obj, err := h.server.Casestore.Create(ctx, inputCase)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Create Case Related Event
// @Description  Attach a related event to an existing case.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.AttachEventCriteria true "Query object used to find original events to attach to a given case. RelatedEvent IDs will be generated by the server."
// @Accept       json
// @Produce      json
// @Success      202  {object}  BulkResp "Returns the bulk operation response"
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/events/ [post]
func (h *CaseHandler) CreateEvents(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	body := model.NewAttachEventCriteria()

	err := web.ReadJson(r, &body)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	criteria := model.NewEventSearchCriteria()

	queryParts := make([]string, 0, len(body.Fields))

	id, ok := body.Fields["soc_id"].(string)
	if ok && id != "" {
		queryParts = append(queryParts, fmt.Sprintf(`_id:"%s"`, id))
	} else {
		ignoredFields := []string{"count"}
		for k, v := range body.Fields {
			if !strings.HasPrefix(k, "soc_") && // not a special soc_ field
				!slices.Contains(ignoredFields, strings.ToLower(k)) && // not part of the ignore list
				reflect.TypeOf(v).Kind() != reflect.Slice && // not a slice
				reflect.TypeOf(v).Kind() != reflect.Array && // ... or array
				!reflect.ValueOf(v).IsZero() { // not a default value
				queryParts = append(queryParts, fmt.Sprintf(`%s:"%v"`, k, v))
			}
		}

		if body.Acknowledged {
			queryParts = append(queryParts, `event.acknowledged:true`)
		} else {
			queryParts = append(queryParts, `NOT event.acknowledged:true`)
		}

		if body.Escalated {
			queryParts = append(queryParts, `event.escalated:true`)
		} else {
			queryParts = append(queryParts, `NOT event.escalated:true`)
		}
	}

	query := strings.Join(queryParts, " AND ")

	maxStr := strconv.Itoa(h.server.Config.ClientParams.AlertingParams.MaxBulkEscalateEvents)

	err = criteria.Populate(query, body.DateRange, body.DateRangeFormat, body.Timezone, "0", maxStr)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	criteria.SortFields = []*model.SortCriteria{
		{
			Field: "@timestamp",
			Order: "desc",
		},
	}

	results, err := h.server.Eventstore.Search(ctx, criteria)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	// convert EventRecord to RelatedEvent
	relatedEvents := make([]*model.RelatedEvent, 0, len(results.Events))
	for _, event := range results.Events {
		related := model.NewRelatedEvent()
		related.CaseId = body.CaseId
		related.Fields = event.Payload
		related.Fields["soc_id"] = event.Id
		related.Fields["soc_timestamp"] = event.Payload["@timestamp"]

		relatedEvents = append(relatedEvents, related)
	}

	noTimeOutCtx := context.Background()
	val := ctx.Value(web.ContextKeyRunAsUsername)
	if val != nil {
		if username, ok := val.(string); ok {
			noTimeOutCtx = context.WithValue(noTimeOutCtx, web.ContextKeyRunAsUsername, username)
		}
	}
	noTimeOutCtx = context.WithValue(noTimeOutCtx, web.ContextKeyRequestorId, ctx.Value(web.ContextKeyRequestorId).(string))
	noTimeOutCtx = log.NewContext(noTimeOutCtx, log.FromContext(ctx))

	go h.createEventsAsync(noTimeOutCtx, relatedEvents)

	web.Respond(w, r, http.StatusAccepted, map[string]interface{}{
		"count": len(relatedEvents),
	})
}

func (h *CaseHandler) createEventsAsync(ctx context.Context, relatedEvents []*model.RelatedEvent) {
	logger := log.FromContext(ctx)

	totalTimeStart := time.Now()
	errMap := map[string]error{}
	created := 0

	defer func() {
		totalTime := time.Since(totalTimeStart)

		withStats := logger.WithFields(log.Fields{
			"errMap":         util.TruncateMap(errMap, 5),
			"totalRequested": len(relatedEvents),
			"totalCreated":   created,
			"totalTime":      totalTime.Seconds(),
		})

		if len(errMap) != 0 {
			withStats.Error("bulk create related events finished")
		} else {
			withStats.Info("bulk create related events finished")
		}

		h.server.Host.Broadcast("related:bulkCreate", "cases", map[string]interface{}{
			"error":    len(errMap),
			"verb":     "create",
			"modified": created,
			"total":    len(relatedEvents),
			"time":     totalTime.Seconds(),
		})
	}()

	var err error

	created, errMap, err = h.server.Casestore.CreateRelatedEvents(ctx, relatedEvents)
	if err != nil {
		logger.WithError(err).WithField("errMap", util.TruncateMap(errMap, 20)).Error("failed to create related events")
	} else {
		logger.WithField("errMap", util.TruncateMap(errMap, 20)).Info("created related events")
	}
}

// @Summary      Create Case Comment
// @Description  Add a new comment to an existing case.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Comment true "New comment object. ID will be generated by the server."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.RelatedEvent   "Outputs the comment object including its generated ID."
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/comments/ [post]
func (h *CaseHandler) createComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	inputComment := model.NewComment()

	err := web.ReadJson(r, &inputComment)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	obj, err := h.server.Casestore.CreateComment(ctx, inputComment)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Create Case Artifact
// @Description  Attach an observable to an existing case.
// @Description  Observables are considered "artifacts" in SOC internal terminology.
// @Description  If not creating a file artifact then only the artifact itself should be sent as the body, in JSON format.
// @Description  If creating a file artifact then two multipart-form values should be supplied: "json" (the artifact object), and "attachment" (the file bytes). The file size, hashes, mime type will be automatically generated and populated into the artifact object on the server.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Artifact true "New case artifact object. ID will be generated by the server."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.Artifact   "Outputs the artifact object including its generated ID."
// @Failure      400        "The provided input object or parameters are malformed or invalid"
// @Failure      401        "Request was not properly authenticated"
// @Failure      403        "Insufficient permissions for this request"
// @Failure      405        "Case module not configured on server"
// @Failure      500        "Internal SOC error; review SOC logs"
// @Router       /connect/case/artifacts/ [post]
func (h *CaseHandler) createArtifact(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	logger := log.FromContext(ctx)
	inputArtifact := model.NewArtifact()

	contentType, ok := r.Header["Content-Type"]
	if !ok || !strings.Contains(contentType[0], "multipart") {
		// Fallback to plain JSON
		logger.WithField("contentType", contentType).Debug("Multipart content type not found")
		err := json.NewDecoder(r.Body).Decode(&inputArtifact)
		if err != nil {
			web.Respond(w, r, http.StatusBadRequest, err)
			return
		}
	} else {
		err := r.ParseMultipartForm(int64(h.server.Config.MaxUploadSizeBytes))
		if err != nil {
			web.Respond(w, r, http.StatusBadRequest, err)
			return
		}

		jsonData := r.FormValue("json")
		err = json.Unmarshal([]byte(jsonData), &inputArtifact)
		if err != nil {
			web.Respond(w, r, http.StatusBadRequest, err)
			return
		}

		logger.Debug("Successfully parsed multipart form")

		// Try pulling an attachment file
		file, handler, err := r.FormFile("attachment")
		if err != nil {
			web.Respond(w, r, http.StatusBadRequest, err)
			return
		}

		if file == nil {
			web.Respond(w, r, http.StatusBadRequest, errors.New("Attachment file not found"))
			return
		}

		logger.Debug("Found attachment")
		defer file.Close()

		if len(inputArtifact.Value) > 0 {
			web.Respond(w, r, http.StatusBadRequest, errors.New("Attachment artifacts must be provided without a value"))
			return
		}

		inputArtifact.Value = handler.Filename
		inputArtifact.ArtifactType = "file"

		artifactStream := model.NewArtifactStream()
		inputArtifact.StreamLen, inputArtifact.MimeType, inputArtifact.Md5, inputArtifact.Sha1, inputArtifact.Sha256, err = artifactStream.Write(file)
		if err != nil {
			web.Respond(w, r, http.StatusInternalServerError, err)
			return
		}

		if inputArtifact.StreamLen != int(handler.Size) {
			logger.WithFields(log.Fields{
				"requestId": ctx.Value(web.ContextKeyRequestId),
				"mimeType":  inputArtifact.MimeType,
				"formLen":   handler.Size,
				"copyLen":   inputArtifact.StreamLen,
			}).Warn("Mismatch of stream size detected")
		} else {
			logger.WithFields(log.Fields{
				"requestId":   ctx.Value(web.ContextKeyRequestId),
				"formFileLen": handler.Size,
				"streamLen":   inputArtifact.StreamLen,
				"mimeType":    inputArtifact.MimeType,
			}).Info("Successfully copied attachment bytes into new artifact stream object")
		}

		var artifactStreamId string
		artifactStreamId, err = h.server.Casestore.CreateArtifactStream(ctx, artifactStream)
		if err != nil {
			web.Respond(w, r, http.StatusInternalServerError, err)
			return
		}

		inputArtifact.StreamId = artifactStreamId
	}

	obj, err := h.server.Casestore.CreateArtifact(ctx, inputArtifact)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Update Case
// @Description  Updates an existing case with a provided case object as input.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Case true "Replacement case object. The provided ID will be used to match the existing case."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.Case   "Outputs the case object."
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      404         "Case not found"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/ [put]
func (h *CaseHandler) updateCase(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	inputCase := model.NewCase()

	err := json.NewDecoder(r.Body).Decode(&inputCase)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	obj, err := h.server.Casestore.Update(ctx, inputCase)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Update Case Comment
// @Description  Updates an existing case comment with a provided comment object as input.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Comment true "Replacement comment object. The provided ID will be used to match the existing comment."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.Comment   "Outputs the case comment object."
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      404         "Case comment not found"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/comments [put]
func (h *CaseHandler) updateComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	inputComment := model.NewComment()

	err := json.NewDecoder(r.Body).Decode(&inputComment)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	obj, err := h.server.Casestore.UpdateComment(ctx, inputComment)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Update Case Artifact
// @Description  Updates an existing case artifact with a provided artifact object as input. Important: The artifact value and type cannot be modified.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        request  body  model.Artifact true "Replacement artifact object. The provided ID will be used to match the existing artifact."
// @Accept       json
// @Produce      json
// @Success      200  {object}  model.Artifact   "Outputs the case artifact object."
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      404         "Case artifact not found"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/artifacts [put]
func (h *CaseHandler) updateArtifact(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	inputArtifact := model.NewArtifact()

	err := json.NewDecoder(r.Body).Decode(&inputArtifact)
	if err != nil {
		web.Respond(w, r, http.StatusBadRequest, err)
		return
	}

	obj, err := h.server.Casestore.UpdateArtifact(ctx, inputArtifact)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Delete Case Comment
// @Description  Removes a case comment from a case and deletes the comment.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        id  path  string  true  "The comment ID to remove"
// @Success      200        "The comment was successfully removed"
// @Failure      400        "The provided input object or parameters are malformed or invalid"
// @Failure      401        "Request was not properly authenticated"
// @Failure      403        "Insufficient permissions for this request"
// @Failure      404        "Case comment not found"
// @Failure      405        "Case module not configured on server"
// @Failure      500        "Internal SOC error; review SOC logs"
// @Router       /connect/case/comments/{id} [delete]
func (h *CaseHandler) deleteComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	err := h.server.Casestore.DeleteComment(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, nil)
}

// @Summary      Delete Case Related Event
// @Description  Removes a related event from a case.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        id  path  string  true  "The related event ID to remove"
// @Success      200        "The related event was successfully removed from the case"
// @Failure      400        "The provided input object or parameters are malformed or invalid"
// @Failure      401        "Request was not properly authenticated"
// @Failure      403        "Insufficient permissions for this request"
// @Failure      404        "Case related event not found"
// @Failure      405        "Case module not configured on server"
// @Failure      500        "Internal SOC error; review SOC logs"
// @Router       /connect/case/events/{id} [delete]
func (h *CaseHandler) deleteEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	err := h.server.Casestore.DeleteRelatedEvent(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, nil)
}

// @Summary      Delete Case Artifact
// @Description  Removes a case artifact.
// @Description  Observables are considered "artifacts" in SOC internal terminology.
// @Tags         Cases
// @Security     bearer[cases/read, cases/write, events/read, events/write]
// @Param        id  path  string  true  "The artifact ID to remove"
// @Success      200       "The artifact was successfully removed from the case"
// @Failure      400       "The provided input object or parameters are malformed or invalid"
// @Failure      401       "Request was not properly authenticated"
// @Failure      403       "Insufficient permissions for this request"
// @Failure      404       "Case artifact not found"
// @Failure      405       "Case module not configured on server"
// @Failure      500       "Internal SOC error; review SOC logs"
// @Router       /connect/case/artifacts/{id} [delete]
func (h *CaseHandler) deleteArtifact(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	err := h.server.Casestore.DeleteArtifact(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, nil)
}

// @Summary      Get Case
// @Description  Retrieves a case given the provided case ID and returns the case details.
// @Description  Use the "Query Data" API to search for cases using other criteria, specifying a query parameter that includes the following, at a minimum: _index:"*:so-case"
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Produce      json
// @Param        id  path  string  true  "The case ID to retrieve"
// @Success      200  {object}  model.Case   "The case object"
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      404         "Case not found"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/{id} [get]
func (h *CaseHandler) getCase(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	obj, err := h.server.Casestore.GetCase(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Get Case Comments
// @Description  Searches for all comments assigned to the given case ID and returns the matching comments, if any.
// @Description  If the case does not exist, this method will respond with a 200 status and an empty list.
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Param        id  path  string  true  "The case ID to use for searching all related comments"
// @Produce      json
// @Success      200  {array}   model.Comment   "The array of case comments, or an empty array if no matching comments found"
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/comments/{id} [get]
func (h *CaseHandler) getComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	obj, err := h.server.Casestore.GetComments(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Get Related Events
// @Description  Searches for all related events associated with the given case ID and returns the matching events, if any.
// @Description  If the case does not exist, this method will respond with a 200 status and an empty list.
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Param        id  path  string  true  "The case ID to use for searching all related events"
// @Produce      json
// @Success      200  {array}   model.RelatedEvent   "The array of related events, or an empty array if no matching events found"
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Router       /connect/case/events/{id} [get]
func (h *CaseHandler) getEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	obj, err := h.server.Casestore.GetRelatedEvents(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Get Artifact Stream
// @Description  Returns the artifact stream for the given artifact ID. Artifact streams are typically file artifacts.
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Param        id  path  string  true  "The artifact's stream ID"
// @Produce      octet-stream
// @Success      200                         "The artifact stream has been successfully retrieved"
// @Failure      400         "The provided input object or parameters are malformed or invalid"
// @Failure      401         "Request was not properly authenticated"
// @Failure      403         "Insufficient permissions for this request"
// @Failure      404         "Artifact stream not found"
// @Failure      405         "Case module not configured on server"
// @Failure      500         "Internal SOC error; review SOC logs"
// @Header       200  {string}  Content-Disposition  "The stream's attachment meta-data. Ex: attachment; filename=foo.zip"
// @Header       200  {string}  Content-Transfer-Encoding  "The encoding type of the response stream. Ex: binary"
// @Router       /connect/case/artifactstream/{id} [get]
func (h *CaseHandler) getTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	err := h.copyArtifactStream(ctx, w, id)
	if err != nil {
		web.Respond(w, r, http.StatusNotFound, nil)
		return
	}

	web.Respond(nil, r, http.StatusOK, nil)
}

// @Summary      Get Case Artifacts
// @Description  Searches for all artifacts attached to the given case ID and returns the matching artifacts, if any.
// @Description  Observables are considered "artifacts" in SOC internal terminology.
// @Description  If the case does not exist, this method will respond with a 200 status and an empty list.
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Param        id  path  string  true  "The case ID to use for searching all artifacts"
// @Produce      json
// @Success      200  {array}   model.Artifact   "The array of artifacts, or an empty array if no matching artifacts found"
// @Failure      400       "The provided input object or parameters are malformed or invalid"
// @Failure      401       "Request was not properly authenticated"
// @Failure      403       "Insufficient permissions for this request"
// @Failure      405       "Case module not configured on server"
// @Failure      500       "Internal SOC error; review SOC logs"
// @Router       /connect/case/artifacts/{id} [get]
func (h *CaseHandler) getArtifact(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	groupType := chi.URLParam(r, "groupType")
	groupId := chi.URLParam(r, "groupID")

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	obj, err := h.server.Casestore.GetArtifacts(ctx, id, groupType, groupId)
	if err != nil {
		web.Respond(w, r, http.StatusInternalServerError, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

// @Summary      Get Case History
// @Description  Returns all audit history associated with the given case ID.
// @Tags         Cases
// @Security     bearer[cases/read, events/read]
// @Param        id  path  string  true  "The case ID"
// @Produce      json
// @Success      200  {array}  model.Auditable  "The array of history audit objects. Note that these objects will also contain either the Case fields, Comment fields, Artifact fields, or RelatedEvent fields."
// @Failure      400        "The provided input object or parameters are malformed or invalid"
// @Failure      401        "Request was not properly authenticated"
// @Failure      403        "Insufficient permissions for this request"
// @Failure      404        "Case not found"
// @Failure      405        "Case module not configured on server"
// @Failure      500        "Internal SOC error; review SOC logs"
// @Router       /connect/case/history/{id} [get]
func (h *CaseHandler) getHistory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id := chi.URLParam(r, "id")
	if id == "" {
		id = r.URL.Query().Get("id")
	}

	obj, err := h.server.Casestore.GetCaseHistory(ctx, id)
	if err != nil {
		web.Respond(w, r, http.StatusNotFound, err)
		return
	}

	web.Respond(w, r, http.StatusOK, obj)
}

func (caseHandler *CaseHandler) copyArtifactStream(ctx context.Context, writer http.ResponseWriter, artifactId string) error {
	logger := log.FromContext(ctx)

	artifact, err := caseHandler.server.Casestore.GetArtifact(ctx, artifactId)
	if err != nil {
		return err
	}

	stream, err := caseHandler.server.Casestore.GetArtifactStream(ctx, artifact.StreamId)
	if err != nil {
		return err
	}

	contentLength := int64(artifact.StreamLen)
	filename := artifact.Value
	content := stream.Read()

	if artifact.Protected {
		buf := bytes.NewBuffer([]byte{})
		zipw := zip.NewWriter(buf)

		filew, err := zipw.Create(filename)
		if err != nil {
			return err
		}

		_, err = io.Copy(filew, content)
		if err != nil {
			return err
		}

		err = zipw.Close()
		if err != nil {
			return err
		}

		content = buf
		contentLength = int64(buf.Len())
		filename += ".zip"
	}

	writer.Header().Set("Content-Type", "application/octet-stream")
	writer.Header().Set("Content-Length", strconv.FormatInt(contentLength, 10))
	writer.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	writer.Header().Set("Content-Transfer-Encoding", "binary")

	written, err := io.Copy(writer, content)
	if err != nil {
		logger.WithError(err).WithFields(log.Fields{
			"artifactName": artifact.Value,
			"artifactId":   artifactId,
		}).Error("Failed to copy artifact stream")

		return err
	}

	logger.WithFields(log.Fields{
		"artifactName":      artifact.Value,
		"artifactSize":      written,
		"artifactId":        artifactId,
		"artifactProtected": artifact.Protected,
	}).Info("Copied artifact stream to response")

	return nil
}
