// Copyright 2019 Jason Ertel (github.com/jertel).
// Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
// or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
// https://securityonion.net/license; you may not use this file except in compliance with the
// Elastic License 2.0.

package export

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/apex/log"
)

func (export *Export) convertMdToPdf(id int, bytes []byte, args []string) (io.Reader, int, error) {
	inputPath := fmt.Sprintf("%s/%d.md", export.tmpPath, id)
	outputPath := fmt.Sprintf("%s/%d.pdf", export.tmpPath, id)
	defer func() {
		os.Remove(inputPath)
		os.Remove(outputPath)
	}()

	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(export.timeoutMs)*time.Millisecond)
	defer func() {
		cancel()
	}()

	err := os.WriteFile(inputPath, bytes, 0644)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to write input file %s: %w", inputPath, err)
	}

	titleArgs := []string{"-title", fmt.Sprintf("Report Job %d", id)}
	args = append(titleArgs, args...)
	args = append(args, "-author", "Generated By Security Onion")
	args = append(args, "-with-footer")
	args = append(args, "-i", inputPath)
	args = append(args, "-o", outputPath)

	cmd := exec.CommandContext(ctx, export.executablePath, args...)
	output, err := cmd.CombinedOutput()
	log.WithFields(log.Fields{
		"executablePath":   export.executablePath,
		"exportArgs":       strings.Join(args, ","),
		"exportJobId":      id,
		"exportOutputPath": outputPath,
		"exportInputPath":  inputPath,
		"exportOutput":     string(output),
		"exportErr":        err,
	}).Debug("Executed document conversion")
	if err != nil {
		return nil, 0, err
	}

	var file *os.File
	var info os.FileInfo
	file, err = os.Open(outputPath)
	if err != nil {
		return nil, 0, err
	}
	info, err = os.Stat(outputPath)
	if err != nil {
		return nil, 0, err
	}
	size := int(info.Size())
	log.WithFields(log.Fields{
		"exportOutputPath": outputPath,
		"exportBytes":      size,
	}).Debug("Read exported file")
	return file, size, err
}
